"""
telegram_sender.py — SocioMee Telegram Integration
====================================================
Sends generated content to Telegram channel/group via Bot API.
No OAuth, no redirect — just BOT_TOKEN + CHAT_ID.

Required .env:
    TELEGRAM_BOT_TOKEN = your_bot_token
    TELEGRAM_CHAT_ID   = your_chat_id (e.g. @yourchannel or -1001234567890)
"""

from __future__ import annotations
import logging, os
from typing import Any, Dict, Optional
import requests

log = logging.getLogger("telegram_sender")

BASE = "https://api.telegram.org"

def _token()   -> str: return os.getenv("TELEGRAM_BOT_TOKEN", "")
def _chat_id() -> str: return os.getenv("TELEGRAM_CHAT_ID",   "")

def _assert_env():
    missing = []
    if not _token():   missing.append("TELEGRAM_BOT_TOKEN")
    if not _chat_id(): missing.append("TELEGRAM_CHAT_ID")
    if missing:
        raise RuntimeError(f"Missing Telegram env vars: {', '.join(missing)}")

def _send(text: str, parse_mode: str = "HTML", disable_preview: bool = True) -> Dict:
    """Send a message to the configured chat."""
    _assert_env()
    # Telegram max message length is 4096 chars
    if len(text) > 4096:
        text = text[:4090] + "\n..."
    resp = requests.post(
        f"{BASE}/bot{_token()}/sendMessage",
        json={
            "chat_id":                  _chat_id(),
            "text":                     text,
            "parse_mode":               parse_mode,
            "disable_web_page_preview": disable_preview,
        },
        timeout=15,
    )
    data = resp.json()
    if not data.get("ok"):
        raise ValueError(f"Telegram error: {data.get('description', 'Unknown error')}")
    return data

def check_connection() -> Dict[str, Any]:
    """Verify bot token + chat ID work."""
    _assert_env()
    # Check bot info
    bot_resp = requests.get(f"{BASE}/bot{_token()}/getMe", timeout=10)
    bot_data = bot_resp.json()
    if not bot_data.get("ok"):
        raise ValueError(f"Invalid bot token: {bot_data.get('description','')}")
    bot = bot_data["result"]
    return {
        "connected":  True,
        "bot_name":   bot.get("first_name", ""),
        "bot_username": bot.get("username", ""),
        "chat_id":    _chat_id(),
    }

def send_script(
    topic:       str,
    platform:    str,
    script_text: str,
    best_title:  str = "",
    hook:        str = "",
    hashtags:    list = None,
    description: str = "",
    is_pro:      bool = False,
) -> Dict[str, Any]:
    """
    Send a full content pack to Telegram.
    Formats beautifully with HTML markup.
    """
    _assert_env()
    msgs_sent = []

    # ── Message 1: Title + Hook ───────────────────────────────────────
    title_line = f"🎯 <b>{best_title or topic.title()}</b>" if best_title else f"📌 <b>{topic.title()}</b>"
    hook_line  = f"\n\n💡 <b>HOOK:</b>\n{hook}" if hook else ""
    platform_emoji = {"youtube":"▶️","instagram":"📸","tiktok":"🎵","x":"𝕏","facebook":"📘","threads":"🧵","telegram":"✈️","pinterest":"📌"}.get(platform.lower(),"📢")

    msg1 = (
        f"{platform_emoji} <b>SocioMee Content Pack</b>\n"
        f"━━━━━━━━━━━━━━━━━━━━\n"
        f"📍 Platform: <b>{platform.upper()}</b>\n"
        f"🔑 Topic: <code>{topic}</code>\n"
        f"━━━━━━━━━━━━━━━━━━━━\n\n"
        f"{title_line}"
        f"{hook_line}"
    )
    r1 = _send(msg1)
    msgs_sent.append(r1["result"]["message_id"])

    # ── Message 2: Script ─────────────────────────────────────────────
    if script_text:
        # Clean script for Telegram (remove HTML-like chars)
        clean = script_text.replace("<", "&lt;").replace(">", "&gt;")
        # Limit to 3000 chars for Telegram
        if len(clean) > 3000:
            clean = clean[:2990] + "\n\n<i>... [Full script in SocioMee]</i>"

        msg2 = (
            f"📜 <b>SCRIPT</b>\n"
            f"━━━━━━━━━━━━━━━━━━━━\n\n"
            f"{clean}"
        )
        r2 = _send(msg2)
        msgs_sent.append(r2["result"]["message_id"])

    # ── Message 3: SEO Pack ───────────────────────────────────────────
    seo_parts = []
    if description:
        desc_preview = description[:500] + ("..." if len(description) > 500 else "")
        seo_parts.append(f"📋 <b>DESCRIPTION (preview):</b>\n<code>{desc_preview}</code>")
    if hashtags:
        tags = " ".join(hashtags[:15])
        seo_parts.append(f"🏷️ <b>HASHTAGS:</b>\n{tags}")

    if seo_parts:
        msg3 = (
            f"🔍 <b>SEO PACK</b>\n"
            f"━━━━━━━━━━━━━━━━━━━━\n\n"
            + "\n\n".join(seo_parts) +
            f"\n\n━━━━━━━━━━━━━━━━━━━━\n"
            f"⚡ Generated by <b>SocioMee AI</b>"
        )
        r3 = _send(msg3)
        msgs_sent.append(r3["result"]["message_id"])

    return {
        "success":      True,
        "messages_sent":len(msgs_sent),
        "message_ids":  msgs_sent,
        "chat_id":      _chat_id(),
    }


def send_quick(text: str) -> Dict[str, Any]:
    """Send a plain quick message to Telegram."""
    _assert_env()
    r = _send(text, parse_mode="HTML")
    return {
        "success":    True,
        "message_id": r["result"]["message_id"],
    }