"""
whatsapp_connect.py — SocioMee WhatsApp Business Cloud API (Option 2)
"""
from __future__ import annotations
import logging, os
from typing import Any, Dict, List
import requests

log = logging.getLogger("whatsapp_connect")
BASE             = "https://graph.facebook.com/v19.0"
PHONE_NUMBER_ID  = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
ACCESS_TOKEN     = os.getenv("WHATSAPP_ACCESS_TOKEN", "")

def _headers():
    return {"Authorization": f"Bearer {ACCESS_TOKEN}", "Content-Type": "application/json"}

def _normalize_number(number: str) -> str:
    number = number.strip().replace(" ", "").replace("-", "").replace("+", "")
    if not number.startswith("91") and len(number) == 10:
        number = "91" + number
    return number

def send_text(to_number: str, text: str) -> Dict[str, Any]:
    if not PHONE_NUMBER_ID or not ACCESS_TOKEN:
        raise ValueError("WhatsApp credentials not configured on server.")
    to_number = _normalize_number(to_number)
    if len(text) > 4096:
        text = text[:4090] + "\n..."
    resp = requests.post(
        f"{BASE}/{PHONE_NUMBER_ID}/messages",
        headers=_headers(),
        json={"messaging_product": "whatsapp", "to": to_number, "type": "text", "text": {"body": text, "preview_url": False}},
        timeout=15,
    )
    data = resp.json()
    if "error" in data:
        raise ValueError(f"WhatsApp send error: {data['error'].get('message', 'Unknown error')}")
    return {"success": True, "message_id": data.get("messages", [{}])[0].get("id", ""), "to": to_number}

def send_content_pack(to_number, topic, platform="whatsapp", script_text="", best_title="", hook="", hashtags=None, description=""):
    if hashtags is None:
        hashtags = []
    emoji = {"youtube":"▶️","instagram":"📸","tiktok":"🎵","facebook":"📘","threads":"🧵","telegram":"✈️","pinterest":"📌","whatsapp":"💬"}.get(platform.lower(), "📢")
    msgs = []
    msg1 = f"{emoji} *SocioMee Content Pack*\n━━━━━━━━━━━━━━━━━━━━\n📍 Platform: *{platform.upper()}*\n🔑 Topic: {topic}\n━━━━━━━━━━━━━━━━━━━━\n\n🎯 *{best_title or topic.title()}*"
    if hook:
        msg1 += f"\n\n💡 *HOOK:*\n{hook}"
    msgs.append(send_text(to_number, msg1).get("message_id", ""))
    if script_text:
        clean = script_text[:2990] + "\n\n... [Full script in SocioMee]" if len(script_text) > 3000 else script_text
        msgs.append(send_text(to_number, f"📜 *SCRIPT*\n━━━━━━━━━━━━━━━━━━━━\n\n{clean}").get("message_id", ""))
    seo = []
    if description:
        seo.append(f"📋 *DESCRIPTION:*\n{description[:400]}...")
    if hashtags:
        seo.append(f"🏷️ *HASHTAGS:*\n{' '.join(hashtags[:15])}")
    if seo:
        msgs.append(send_text(to_number, "🔍 *SEO PACK*\n━━━━━━━━━━━━━━━━━━━━\n\n" + "\n\n".join(seo) + "\n\n⚡ Generated by *SocioMee AI*").get("message_id", ""))
    return {"success": True, "messages_sent": len(msgs), "message_ids": msgs, "to": to_number}

def get_best_send_times():
    return {
        "best_times": [
            {"day": "Monday", "time": "08:00 AM", "reason": "Start of week, high open rate"},
            {"day": "Wednesday", "time": "07:30 PM", "reason": "Mid-week evening peak"},
            {"day": "Friday", "time": "06:00 PM", "reason": "Weekend start, highest engagement"},
            {"day": "Sunday", "time": "10:00 AM", "reason": "Relaxed morning browsing"},
        ],
        "avoid": [
            {"time": "12:00 AM - 07:00 AM", "reason": "Low open rate, do not disturb"},
            {"time": "02:00 PM - 04:00 PM", "reason": "Post-lunch dip"},
        ],
        "india_peak": "7:00 PM - 10:00 PM IST",
        "tip": "WhatsApp messages sent between 7-10 PM IST get 40% higher open rates in India",
    }
