import { useState } from "react";
const C={blue:"#1877f2",glass:"rgba(255,255,255,0.04)",hairline:"rgba(255,255,255,0.08)",ink:"rgba(255,255,255,0.9)",muted:"rgba(255,255,255,0.4)",success:"#34d399",danger:"#f87171"};
const AI="https://sociomeeai.com/api/ai/generate";
let lastCall=0;
const BAD_WORDS=['fuck','shit','bitch','bastard','asshole','nigger','faggot','chutiya','madarchod','bhenchod','randi','harami','gandu','motherfucker','child porn','cocaine','heroin','meth','jihad','massacre','genocide','bomb','suicide','how to kill','terrorist','explosive','drug deal','buy guns','illegal weapons','human trafficking','rape','molest','hack into','ransomware','darkweb','money laundering','assassination'];
function filterBad(t){let s=t;BAD_WORDS.forEach(w=>{const re=new RegExp('\\b'+w+'\\b','gi');s=s.replace(re,'*'.repeat(w.length));});return s;}
async function askGemini(prompt){const now=Date.now();if(now-lastCall<3000)await new Promise(r=>setTimeout(r,3000-(now-lastCall)));lastCall=Date.now();try{const r=await fetch(AI,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[{role:"user",content:prompt}]})});if(!r.ok)return"";const d=await r.json();return d.content?.[0]?.text||"";}catch{return"";}}
function parseJSON(text){try{const c=text.replace(/```json|```/g,"").trim();const m=c.match(/(\[[\s\S]*\]|\{[\s\S]*\})/);return JSON.parse(m?m[1]:c);}catch{return null;}}
function ToolCard({title,icon,children}){return <div style={{maxWidth:"700px",margin:"0 auto",padding:"20px 16px"}}><div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"20px"}}><span style={{fontSize:"20px"}}>{icon}</span><h2 style={{fontSize:"18px",fontWeight:"900",color:"#fff",margin:0}}>{title}</h2></div>{children}</div>;}
function GlassCard({children,style={}}){return <div style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"16px",padding:"20px",...style}}>{children}</div>;}
function GenButton({onClick,loading,label="✦ Generate"}){return <button onClick={onClick} disabled={loading} style={{width:"100%",padding:"14px",borderRadius:"99px",border:"1.5px solid rgba(24,119,242,0.6)",background:loading?"rgba(24,119,242,0.05)":"rgba(24,119,242,0.15)",backdropFilter:"blur(16px)",color:"#fff",fontWeight:"800",fontSize:"14px",cursor:loading?"not-allowed":"pointer",fontFamily:"inherit",boxShadow:loading?"none":"0 0 24px rgba(24,119,242,0.4)",transition:"all 0.3s",opacity:loading?0.6:1}}>{loading?"Generating…":label}</button>;}
function NichePills({niches,active,onSelect}){return <div style={{display:"flex",gap:"6px",flexWrap:"wrap"}}>{niches.map(n=>{const isActive=active===n.toLowerCase();return <button key={n} onClick={()=>onSelect(n.toLowerCase())} style={{padding:"5px 12px",borderRadius:"99px",border:`1.5px solid ${isActive?"rgba(24,119,242,0.7)":"rgba(255,255,255,0.1)"}`,background:isActive?"rgba(24,119,242,0.15)":"transparent",color:isActive?"#93c5fd":"rgba(255,255,255,0.5)",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{n}</button>;})}</div>;}
function Skeleton({lines=3}){return <div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{Array(lines).fill(0).map((_,i)=><GlassCard key={i}><div style={{display:"flex",flexDirection:"column",gap:"10px"}}><div style={{height:"12px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"40%"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"70%"}}/></div></GlassCard>)}<style>{`@keyframes shimmer{to{background-position:-200% 0}}`}</style></div>;}

const POST_FB={business:["🚀 Big news for our {topic} community!\n\nWe've been working behind the scenes on something special.\n\nDrop a 🔥 in the comments if you want to be the first to know!\n\n👉 Share this with someone who needs to see it","💡 Quick tip about {topic} that changed everything:\n\nStop trying to be perfect. Start trying to be consistent.\n\nThe businesses winning right now aren't the smartest — they're the most consistent.\n\nWhat's your consistency strategy? 👇"],food:["😍 This {topic} recipe is breaking the internet for a reason!\n\nBest part? Only 5 ingredients.\n\nSave this post before you forget 😅\nTag a friend who NEEDS to try this! 👇\n\n#Recipe #FoodLovers #HomeCooking","🍽️ POV: You just discovered the best {topic} recipe of your life.\n\n✅ Ready in 30 minutes\n✅ Budget-friendly\n✅ Family approved\n\nDrop ❤️ if you want the full recipe in comments!"],motivational:["Good morning! 🌅\n\n{topic} is not about being perfect.\nIt's about showing up every single day.\n\nThe person you'll be in 1 year is built from what you do TODAY.\n\nLike this if it hit home 💪\nShare with someone who needs this!","You're closer than you think. 💙\n\n{topic} might feel impossible right now.\nBut every expert was once a beginner.\n\nYour step today: Just start. Everything else figures itself out.\n\nTag someone who needs to hear this 👇"],general:["We have a question for our community! 🤔\n\nWhen it comes to {topic}:\n\n🅐 Just getting started\n🅑 Been doing it for a while\n🅒 Consider myself an expert\n🅓 Want to learn more\n\nComment your answer! We read every single one 💬","📌 Save this post — you'll thank us later!\n\n{topic} seems complicated at first but once you get it, you get it.\n\nSimple truth:\n→ Start small\n→ Stay consistent\n→ Trust the process\n\nShare with someone overthinking this! 👇"],news:["🔴 JUST IN: {topic}\n\nHere's what you need to know:\n✦ What happened\n✦ Why it matters to YOU\n✦ What comes next\n\nFull breakdown in comments 👇\nShare so your friends don't miss it!","⚡ UPDATE on {topic}:\n\nThings are moving fast. Here's the latest.\n\nFollow our page for real-time updates 🔔\nShare with friends following this story!"]};
const GROUP_FB=[{title:"Community Question",post:"👋 Quick question for the group!\n\nWhen it comes to {topic}, what's been your biggest challenge?\n\nA) Getting started\nB) Staying consistent\nC) Seeing results\nD) Something else\n\nComment below — I'll share what's worked for me! 💬"},{title:"Share Your Win",post:"🏆 WIN WEDNESDAY!\n\nI want to celebrate the wins in this group!\n\nShare your biggest {topic} win this week — big or small, every win counts.\n\nDrop yours below 👇 Let's hype each other up!"},{title:"Value Share",post:"📚 Sharing something that changed how I think about {topic}:\n\nThe reason this works:\n→ It focuses on consistency over perfection\n→ It removes the overwhelm\n→ Anyone can start today\n\nHas anyone else experienced this? What would you add? 💬"}];
const AD_FB=[{headline:"Stop Struggling With {topic}",primary:"Thousands of people are getting real results with our approach to {topic}. No complicated strategies. No fluff. Just what actually works.\n\nJoin them today — completely free to start.",cta:"Learn More"},{headline:"The {topic} Solution You Need",primary:"Finally — a simple, effective way to handle {topic}. We've helped thousands transform their approach. Results guaranteed or your money back.\n\nSee how it works today.",cta:"Get Started Free"},{headline:"Why Everyone's Talking About {topic}",primary:"Here's the truth about {topic} most people don't know. Our proven method has helped thousands get real results. Try it completely free.",cta:"See How It Works"}];
const TIME_FB={india:{times:[{time:"9:00 AM – 11:00 AM IST",reason:"Morning Facebook check — Indian users most active before work",score:92,day:"All days"},{time:"7:00 PM – 9:00 PM IST",reason:"Evening prime time — family time on Facebook in India",score:95,day:"All days"},{time:"12:00 PM – 2:00 PM IST",reason:"Lunch break scrolling — massive mobile usage spike",score:85,day:"Weekdays"},{time:"9:00 PM – 11:00 PM IST",reason:"Late evening browsing — second highest engagement window",score:88,day:"All days"}],best_days:["Wednesday","Thursday","Friday","Sunday"],avoid:["Early morning before 8 AM","Monday morning"],tip:"Facebook pages reach more people with video — even simple text-on-screen videos get 3x more reach than images. Hindi/regional language posts get 5x more comments from Indian audience.",frequency:"1-2 posts per day for pages, 3-5 per week for groups."},global:{times:[{time:"1:00 PM – 3:00 PM EST",reason:"US afternoon peak — highest engagement across all demographics",score:94,day:"Weekdays"},{time:"7:00 PM – 9:00 PM EST",reason:"Prime time — families and adults most active",score:91,day:"All days"},{time:"9:00 AM – 11:00 AM EST",reason:"Morning routine check — coffee scrolling peak",score:86,day:"Weekdays"}],best_days:["Thursday","Friday","Saturday","Sunday"],avoid:["Monday morning","Tuesday before noon"],tip:"Facebook algorithm rewards content that generates comments over likes. Ask genuine questions. Respond to every comment in the first hour to boost reach by up to 50%.",frequency:"1 post per day for maximum reach without audience fatigue."}};

export function FacebookPost(){
  const [topic,setTopic]=useState("");const [niche,setNiche]=useState("general");const [type,setType]=useState("engagement");const [posts,setPosts]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["General","Business","Food","Travel","Fitness","Fashion","Motivational","News","Entertainment","Education","Bollywood","Cricket","Technology","Real Estate","Finance","Parenting","Health","Gaming","Music","Pets","Comedy","Devotional","Wedding","Politics","Automobile","Agriculture","Beauty","Cooking","Yoga","Astrology"];
  const types=["Engagement","Viral/Share","Informative","Story","Poll","News Update"];
  const getFallback=(topic,niche)=>{const pool=POST_FB[niche]||POST_FB.general;const tag=topic.replace(/\s+/g,"");return[...pool].sort(()=>Math.random()-0.5).slice(0,2).map(p=>filterBad(p.replace(/{topic}/g,topic).replace(/{topicTag}/g,tag)));};
  const generate=async()=>{if(!topic.trim())return;setLoading(true);setPosts([]);const text=await askGemini(`Write 2 viral Facebook posts about: "${filterBad(topic)}" niche: ${niche} type: ${type}..
RULES: 1) First 3 lines show before See More — make them count. Emotional hook, surprising fact, or relatable situation. 2) 6-10 emojis placed naturally throughout. 3) Warm conversational tone like talking to a friend. 4) For poll type: use 🅐🅑🅒🅓 format. For viral: include "Tag someone who...". For story: raw personal and real. 5) Indian context: reference festivals, cricket, Bollywood, family dynamics, regional culture where relevant. Mix 1-2 Hindi words naturally (yaar, bilkul, ekdum) for Indian niches. 6) 120-200 words + hashtags. 7) Strong end CTA: question/tag/share/save. 8) 5-8 hashtags.
Return ONLY a valid JSON array of 2 strings. No markdown.`);const parsed=parseJSON(text);setPosts((parsed&&Array.isArray(parsed)&&parsed.length)?parsed:getFallback(topic,niche));setLoading(false);};
  return(<ToolCard title="Post Caption Generator" icon="📝"><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TOPIC / IDEA</div><input value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>e.key==="Enter"&&generate()} placeholder="e.g. Diwali celebration, new product launch, fitness tip" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><div style={{marginBottom:"14px"}}><NichePills niches={niches} active={niche} onSelect={setNiche}/></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>POST TYPE</div><div style={{marginBottom:"16px"}}><NichePills niches={types} active={type} onSelect={setType}/></div><GenButton onClick={generate} loading={loading} label="✦ Generate Facebook Captions"/></GlassCard>
  {loading&&<Skeleton lines={2}/>}
  {!loading&&posts.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{posts.map((p,i)=><GlassCard key={i} style={{cursor:"pointer",borderLeft:"3px solid #1877f2"}} onClick={()=>{navigator.clipboard.writeText(p);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"10px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>Post {i+1}</div><div style={{fontSize:"11px",color:copied===i?C.success:"#93c5fd",fontWeight:"600"}}>{copied===i?"✓ Copied":"Copy"}</div></div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.85)",lineHeight:1.8,whiteSpace:"pre-line"}}>{p}</div><div style={{marginTop:"10px",fontSize:"10px",color:C.muted}}>{p.length} chars</div></GlassCard>)}<GlassCard style={{borderLeft:"3px solid #1877f2"}}><div style={{fontSize:"10px",fontWeight:"700",color:"#93c5fd",marginBottom:"6px"}}>📘 FACEBOOK TIP</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.6)",lineHeight:1.6}}>Posts with questions get 100% more comments. First 3 lines show before "See More" — make them count. Video gets 3x more organic reach. Respond to comments within 1 hour.</div></GlassCard></div>}
  </ToolCard>);}

export function FacebookGroupPost(){
  const [topic,setTopic]=useState("");const [goal,setGoal]=useState("engagement");const [posts,setPosts]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const goals=["Engagement","Share a Win","Ask for Help","Value Share","Weekly Challenge","Introduce Yourself","Poll"];
  const getFallback=(topic)=>GROUP_FB.map(p=>({...p,post:filterBad(p.post.replace(/{topic}/g,topic))}));
  const generate=async()=>{if(!topic.trim())return;setLoading(true);setPosts([]);const text=await askGemini(`Write 3 Facebook GROUP post templates for: "${filterBad(topic)}" goal: "${goal}". Group posts are personal and community-first. Use "I" and "we" naturally. Ask genuine questions. 80-200 words each. Warm inclusive tone like a community leader. Include emoji naturally. For Indian groups mix Hindi phrases if fitting. Return ONLY a valid JSON array of 3 objects: [{"title":"post title","post":"full post text"}]. No markdown.`);const parsed=parseJSON(text);setPosts((parsed&&Array.isArray(parsed)&&parsed.length)?parsed:getFallback(topic));setLoading(false);};
  return(<ToolCard title="Group Post Generator" icon="👥"><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TOPIC / THEME</div><input value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>e.key==="Enter"&&generate()} placeholder="e.g. fitness journey, startup lessons, cooking tips" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>POST GOAL</div><div style={{marginBottom:"16px"}}><NichePills niches={goals} active={goal} onSelect={setGoal}/></div><GenButton onClick={generate} loading={loading} label="✦ Generate Group Posts"/></GlassCard>
  {loading&&<Skeleton lines={3}/>}
  {!loading&&posts.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{posts.map((p,i)=><GlassCard key={i} style={{borderLeft:"3px solid #1877f2"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"8px"}}><div style={{fontSize:"12px",fontWeight:"700",color:"#93c5fd"}}>{p.title||`Template ${i+1}`}</div><button onClick={()=>{navigator.clipboard.writeText(p.post||p);setCopied(i);setTimeout(()=>setCopied(null),2000);}} style={{padding:"5px 12px",borderRadius:"99px",border:"1px solid rgba(24,119,242,0.3)",background:"rgba(24,119,242,0.1)",color:copied===i?C.success:"#93c5fd",fontSize:"11px",fontWeight:"700",cursor:"pointer",fontFamily:"inherit"}}>{copied===i?"✓ Copied":"Copy"}</button></div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.85)",lineHeight:1.8,whiteSpace:"pre-line"}}>{p.post||p}</div></GlassCard>)}</div>}
  </ToolCard>);}

export function FacebookAdCopy(){
  const [product,setProduct]=useState("");const [audience,setAudience]=useState("");const [goal,setGoal]=useState("conversions");const [ads,setAds]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const goals=["Conversions","Lead Generation","Brand Awareness","Traffic","App Installs","Engagement"];
  const getFallback=(product)=>AD_FB.map(a=>({headline:filterBad(a.headline.replace(/{topic}/g,product)),primary:filterBad(a.primary.replace(/{topic}/g,product)),cta:a.cta}));
  const generate=async()=>{if(!product.trim())return;setLoading(true);setAds([]);const text=await askGemini(`Write 3 Facebook ad copies for: "${filterBad(product)}" audience: "${filterBad(audience||"general")}" goal: ${goal}. Each needs: headline max 40 chars attention-grabbing, primary text 100-150 words problem-agitate-solve formula, CTA one of [Shop Now, Learn More, Sign Up, Get Started, Book Now, Download]. For Indian market include INR if relevant. No fake claims. Return ONLY a valid JSON array of 3 objects: [{"headline":"...","primary":"...","cta":"..."}]. No markdown.`);const parsed=parseJSON(text);setAds((parsed&&Array.isArray(parsed)&&parsed.length)?parsed:getFallback(product));setLoading(false);};
  return(<ToolCard title="Ad Copy Generator" icon="📢"><GlassCard style={{marginBottom:"16px"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"14px"}}><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>PRODUCT / SERVICE *</div><input value={product} onChange={e=>setProduct(e.target.value)} placeholder="e.g. Online yoga course, SaaS tool, clothing brand" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TARGET AUDIENCE</div><input value={audience} onChange={e=>setAudience(e.target.value)} placeholder="e.g. Indian women 25-40, startup founders" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>CAMPAIGN GOAL</div><div style={{marginBottom:"16px"}}><NichePills niches={goals} active={goal} onSelect={setGoal}/></div><GenButton onClick={generate} loading={loading} label="✦ Generate Ad Copies"/></GlassCard>
  {loading&&<Skeleton lines={3}/>}
  {!loading&&ads.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{ads.map((ad,i)=><GlassCard key={i} style={{borderLeft:"3px solid #1877f2"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"12px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>Ad Variation {i+1}</div><button onClick={()=>{navigator.clipboard.writeText(`Headline: ${ad.headline}\n\nPrimary Text:\n${ad.primary}\n\nCTA: ${ad.cta}`);setCopied(i);setTimeout(()=>setCopied(null),2000);}} style={{padding:"5px 12px",borderRadius:"99px",border:"1px solid rgba(24,119,242,0.3)",background:"rgba(24,119,242,0.1)",color:copied===i?C.success:"#93c5fd",fontSize:"11px",fontWeight:"700",cursor:"pointer",fontFamily:"inherit"}}>{copied===i?"✓ Copied":"Copy All"}</button></div><div style={{marginBottom:"10px",padding:"10px 14px",borderRadius:"10px",background:"rgba(24,119,242,0.1)",border:"1px solid rgba(24,119,242,0.2)"}}><div style={{fontSize:"10px",fontWeight:"700",color:"#93c5fd",marginBottom:"4px",textTransform:"uppercase"}}>Headline</div><div style={{fontSize:"15px",fontWeight:"800",color:"#fff"}}>{ad.headline}</div><div style={{fontSize:"10px",color:ad.headline?.length>40?C.danger:C.muted,marginTop:"4px"}}>{ad.headline?.length||0}/40 chars</div></div><div style={{marginBottom:"10px"}}><div style={{fontSize:"10px",fontWeight:"700",color:C.muted,marginBottom:"6px",textTransform:"uppercase"}}>Primary Text</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.8)",lineHeight:1.7,whiteSpace:"pre-line"}}>{ad.primary}</div></div><div style={{display:"inline-flex",alignItems:"center",gap:"8px",padding:"6px 14px",borderRadius:"8px",background:"rgba(24,119,242,0.15)",border:"1px solid rgba(24,119,242,0.3)"}}><div style={{fontSize:"10px",fontWeight:"700",color:"#93c5fd",textTransform:"uppercase"}}>CTA:</div><div style={{fontSize:"12px",fontWeight:"800",color:"#fff"}}>{ad.cta}</div></div></GlassCard>)}<GlassCard style={{borderLeft:"3px solid #1877f2"}}><div style={{fontSize:"10px",fontWeight:"700",color:"#93c5fd",marginBottom:"6px"}}>📢 FB ADS TIP</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.6)",lineHeight:1.6}}>Test 3 variations with ₹200/day budget for 3 days. Kill the 2 losers. Scale the winner. Always test one variable at a time — headline OR image OR audience. Never change everything at once.</div></GlassCard></div>}
  </ToolCard>);}

export function FacebookBestTime(){
  const [niche,setNiche]=useState("general");const [audience,setAudience]=useState("india");const [result,setResult]=useState(null);const [loading,setLoading]=useState(false);
  const niches=["general","business","food","travel","fitness","fashion","news","entertainment","education","bollywood","cricket","technology","real estate","finance","parenting","health","gaming","music","pets","motivational"];
  const audiences=[{id:"india",label:"India (IST)"},{id:"global",label:"Global (EST)"},{id:"uk",label:"UK & Europe"},{id:"usa",label:"USA"},{id:"middle_east",label:"Middle East"},{id:"australia",label:"Australia"}];
  const analyze=async()=>{setLoading(true);setResult(null);const text=await askGemini(`Best times to post on Facebook for niche: "${niche}" audience: "${audience}". Return ONLY valid JSON: {"times":[{"time":"7:00 PM – 9:00 PM IST","reason":"reason","score":95,"day":"All days"}],"best_days":["Wednesday"],"avoid":["Monday morning"],"tip":"specific actionable Facebook tip","frequency":"X posts per day"} 3-4 time slots. Score out of 100.`);const parsed=parseJSON(text);setResult((parsed&&parsed.times)?parsed:(TIME_FB[audience]||TIME_FB.india));setLoading(false);};
  const scoreColor=s=>s>=90?"#34d399":s>=80?"#f59e0b":"#f87171";
  return(<ToolCard title="Best Time to Post" icon="⏰"><GlassCard style={{marginBottom:"16px"}}><div style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><NichePills niches={niches} active={niche} onSelect={setNiche}/></div><div style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>AUDIENCE</div><div style={{display:"flex",flexWrap:"wrap",gap:"6px"}}>{audiences.map(a=><button key={a.id} onClick={()=>setAudience(a.id)} style={{padding:"5px 14px",borderRadius:"99px",border:`1.5px solid ${audience===a.id?"rgba(24,119,242,0.7)":"rgba(255,255,255,0.1)"}`,background:audience===a.id?"rgba(24,119,242,0.15)":"transparent",color:audience===a.id?"#93c5fd":"rgba(255,255,255,0.5)",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{a.label}</button>)}</div></div><GenButton onClick={analyze} loading={loading} label="✦ Analyze Best Times"/></GlassCard>
  {loading&&<Skeleton lines={3}/>}
  {!loading&&result&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}><GlassCard><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"12px"}}>🕐 Best Times</div>{result.times?.map((t,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:"12px",padding:"10px 14px",borderRadius:"12px",background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.06)",marginBottom:"8px"}}><div style={{fontSize:"20px",fontWeight:"900",color:scoreColor(t.score),minWidth:"36px",textAlign:"center"}}>{t.score}</div><div style={{flex:1}}><div style={{fontSize:"13px",fontWeight:"700",color:"#fff",marginBottom:"2px"}}>{t.time} <span style={{fontSize:"10px",color:C.muted}}>· {t.day}</span></div><div style={{fontSize:"11px",color:C.muted}}>{t.reason}</div></div><div style={{width:"5px",height:"36px",borderRadius:"99px",background:scoreColor(t.score),opacity:0.7}}/></div>)}</GlassCard><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px"}}><GlassCard><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"10px"}}>✅ Best Days</div>{result.best_days?.map((d,i)=><div key={i} style={{fontSize:"13px",color:"#34d399",fontWeight:"600",marginBottom:"4px"}}>• {d}</div>)}</GlassCard><GlassCard><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"10px"}}>❌ Avoid</div>{result.avoid?.map((d,i)=><div key={i} style={{fontSize:"11px",color:"#f87171",fontWeight:"600",marginBottom:"4px"}}>• {d}</div>)}</GlassCard></div><GlassCard style={{borderLeft:"3px solid #1877f2"}}><div style={{fontSize:"10px",fontWeight:"700",color:"#93c5fd",marginBottom:"6px"}}>📘 FACEBOOK PRO TIP</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.8)",lineHeight:1.6,marginBottom:"8px"}}>{result.tip}</div><div style={{fontSize:"12px",color:C.muted}}>📅 <span style={{color:"#93c5fd",fontWeight:"700"}}>{result.frequency}</span></div></GlassCard></div>}
  </ToolCard>);}
