import { useState } from "react";
const C={blue:"#0077b5",glass:"rgba(255,255,255,0.04)",hairline:"rgba(255,255,255,0.08)",ink:"rgba(255,255,255,0.9)",muted:"rgba(255,255,255,0.4)",success:"#34d399",danger:"#f87171"};
const AI="https://sociomeeai.com/api/ai/generate";
let lastCall=0;
const BAD_WORDS=['fuck','shit','bitch','bastard','asshole','nigger','faggot','chutiya','madarchod','bhenchod','randi','harami','gandu','motherfucker','child porn','cocaine','heroin','meth','jihad','massacre','genocide','bomb','suicide','how to kill','terrorist','explosive','drug deal','buy guns','illegal weapons','human trafficking','rape','molest','hack into','ransomware','darkweb','money laundering','assassination'];
function filterBad(t){let s=t;BAD_WORDS.forEach(w=>{const re=new RegExp('\\b'+w+'\\b','gi');s=s.replace(re,'*'.repeat(w.length));});return s;}
async function askGemini(prompt){const now=Date.now();if(now-lastCall<3000)await new Promise(r=>setTimeout(r,3000-(now-lastCall)));lastCall=Date.now();try{const r=await fetch(AI,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[{role:"user",content:prompt}],cost:2})});if(!r.ok)return"";const d=await r.json();if(d.credit_status)window.dispatchEvent(new CustomEvent("sociomee-credits-updated",{detail:d.credit_status}));return d.content?.[0]?.text||"";}catch{return"";}}
function parseJSON(text){try{const c=text.replace(/```json|```/g,"").trim();const m=c.match(/(\[[\s\S]*\]|\{[\s\S]*\})/);return JSON.parse(m?m[1]:c);}catch{return null;}}
function stripDashes(s){return typeof s==="string"?s.replace(/[\u2013\u2014-]/g," "):s;}
function ToolCard({title,icon,children}){return <div style={{maxWidth:"700px",margin:"0 auto",padding:"20px 16px"}}><div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"20px"}}><span style={{fontSize:"20px"}}>{icon}</span><h2 style={{fontSize:"18px",fontWeight:"900",color:"#fff",margin:0}}>{title}</h2></div>{children}</div>;}
function GlassCard({children,style={}}){return <div style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"16px",padding:"20px",...style}}>{children}</div>;}
function GenButton({onClick,loading,label="✦ Generate"}){return <button onClick={onClick} disabled={loading} style={{width:"100%",padding:"14px",borderRadius:"99px",border:"1.5px solid rgba(0,119,181,0.6)",background:loading?"rgba(0,119,181,0.05)":"rgba(0,119,181,0.15)",backdropFilter:"blur(16px)",color:"#fff",fontWeight:"800",fontSize:"14px",cursor:loading?"not-allowed":"pointer",fontFamily:"inherit",boxShadow:"none",transition:"all 0.3s",opacity:loading?0.6:1}}>{loading?"Generating…":label}</button>;}
function NichePills({niches,active,onSelect}){return <div style={{display:"flex",gap:"6px",flexWrap:"wrap"}}>{niches.map(n=>{const isActive=active===n.toLowerCase();return <button key={n} onClick={()=>onSelect(n.toLowerCase())} style={{padding:"5px 12px",borderRadius:"99px",border:`1.5px solid ${isActive?"rgba(0,119,181,0.7)":"rgba(255,255,255,0.1)"}`,background:isActive?"rgba(0,119,181,0.15)":"transparent",color:isActive?"#60a5fa":"rgba(255,255,255,0.5)",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{n}</button>;})}</div>;}
function Skeleton({lines=3}){return <div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{Array(lines).fill(0).map((_,i)=><GlassCard key={i}><div style={{display:"flex",flexDirection:"column",gap:"10px"}}><div style={{height:"12px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"40%"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"70%"}}/></div></GlassCard>)}<style>{`@keyframes shimmer{to{background-position:-200% 0}}`}</style></div>;}

const POST_FB={tech:["🚀 {topic} is changing how we work — and most professionals haven't caught up yet.\n\nHere's what I've learned:\n\n→ The learning curve is shorter than you think\n→ Early adopters are getting a massive competitive edge\n→ The question isn't if you should use it — it's when\n\nWhat's your take? Drop it below 👇\n\n#Technology #Innovation #FutureOfWork #LinkedIn","⚡ Unpopular opinion: most people are approaching {topic} completely wrong.\n\nAfter testing it extensively:\n\n1. Stop trying to replace your workflow immediately\n2. Start with one specific use case\n3. Measure the time saved ruthlessly\n\nThe professionals winning with {topic} aren't the most technical. They're the most systematic.\n\n#Tech #Productivity #Growth"],startup:["💡 Building a startup taught me things no MBA could.\n\n{topic} was my biggest lesson.\n\nYear 1: I ignored it completely\nYear 2: I tried to shortcut it\nYear 3: I finally respected it\n\nThe result? Everything changed in year 3.\n\nFounders — what's your {topic} story? 👇\n\n#Startup #Entrepreneurship #Founder #BuildingInPublic","🔥 The brutal truth about {topic} that startup gurus won't tell you:\n\nIt's not glamorous. It's not fast.\nBut it's the difference between startups that survive and ones that don't.\n\n#StartupLife #Entrepreneurship #RealTalk"],marketing:["📊 {topic} changed our results completely.\n\nBefore: Average engagement, average results\nAfter: 3x more meaningful conversations\n\nThe strategy wasn't complicated. The execution was.\n\n→ Stopped chasing vanity metrics\n→ Started measuring what actually matters\n→ Built systems instead of one-off campaigns\n\nWhat's working in your marketing right now? 👇\n\n#Marketing #Growth #B2B"],general:["💡 {topic} — here's what 3 years of experience taught me that no one talks about:\n\nEveryone focuses on the exciting parts.\nNobody talks about the hard middle.\n\nThe hard middle is where most people quit.\nThe hard middle is also where all the growth happens.\n\n#Growth #Mindset #ProfessionalDevelopment","🔑 The {topic} insight that changed how I approach everything:\n\nStop optimizing for looking good.\nStart optimizing for getting better.\n\nSimple. Hard. True.\n\n#PersonalGrowth #Leadership #ProfessionalDevelopment"]};
const HL_FB={tech:["Software Engineer | Building scalable systems | Passionate about AI & the future of tech","Full Stack Developer | Turning complex problems into elegant solutions | Open to opportunities","Tech Lead | 5+ years in product engineering | Helping teams build better software faster"],marketing:["Marketing Strategist | Helping B2B brands grow through content & SEO","Digital Marketing Lead | Driving growth through data-driven campaigns | Speaker","Brand Builder | Content Strategy | Demand Generation | Turning audiences into customers"],general:["{role} | {specialty} | Helping professionals achieve more","{role} | Passionate about {topic} | Always learning, always building","{role} | 5+ years of experience | Speaker | Mentor | Sharing what I learn"]};
const TIME_FB={india:{times:[{time:"8:00 AM – 10:00 AM IST",reason:"Indian professionals check LinkedIn before work — highest open rates",score:96,day:"Tue–Thu"},{time:"12:00 PM – 1:00 PM IST",reason:"Lunch break browsing — decision makers most active",score:88,day:"Weekdays"},{time:"6:00 PM – 8:00 PM IST",reason:"Post-work professional browsing",score:85,day:"Weekdays"}],best_days:["Tuesday","Wednesday","Thursday"],avoid:["Monday morning","Friday afternoon","Weekends"],tip:"Indian LinkedIn audience peaks Tue–Thu morning. First comment matters — add value immediately after posting. Tag relevant people (not spam).",frequency:"3-5 posts per week. Consistency beats virality on LinkedIn."},global:{times:[{time:"7:00 AM – 9:00 AM EST",reason:"US east coast professionals — largest LinkedIn demographic",score:94,day:"Tue–Thu"},{time:"12:00 PM – 1:00 PM EST",reason:"Global lunch break — highest cross-timezone overlap",score:89,day:"Weekdays"},{time:"5:00 PM – 6:00 PM EST",reason:"End of day check — professionals wrapping up",score:83,day:"Tue–Thu"}],best_days:["Tuesday","Wednesday","Thursday"],avoid:["Monday morning","Friday afternoon","Weekends"],tip:"Reply to every comment in the first hour. No links in post body — put them in first comment. LinkedIn rewards dwell time so write longer posts.",frequency:"3-5 posts per week for maximum algorithm reach."}};

export function LinkedInPost(){
  const [topic,setTopic]=useState("");const [niche,setNiche]=useState("general");const [tone,setTone]=useState("thought leadership");const [posts,setPosts]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["General","Tech","Startup","Marketing","Finance","Sales","Leadership","HR","Design","Product","AI","Consulting","Healthcare","Education","Real Estate","Legal","Creator Economy","India","Manufacturing","Logistics","Edtech","Fintech","Retail","Agriculture","Media","Journalism","Law","Architecture","Automotive","Fashion","Gaming","Sports"];
  const tones=["Thought Leadership","Personal Story","Controversial Take","Educational","Motivational","Data-driven"];
  const getFallback=(topic,niche)=>{const pool=POST_FB[niche]||POST_FB.general;return [...pool].sort(()=>Math.random()-0.5).slice(0,2).map(p=>filterBad(p.replace(/{topic}/g,topic)));};
  const generate=async()=>{if(!topic.trim())return;setLoading(true);setPosts([]);const text=await askGemini(`Write 2 viral LinkedIn posts about: "${filterBad(topic)}" niche: ${niche} tone: ${tone}..
RULES: 1) First line MUST stop scroll, using a bold claim, shocking stat, personal failure, or "X years ago I..." NEVER start with "excited to share". 2) 150 to 250 words sweet spot. 3) Short paragraphs of 1 to 2 lines max, white space is king. 4) Use → or ▸ for lists. 5) Flow: Hook then Insight then Lesson then Question CTA. 6) Indian context where relevant: startup ecosystem, Shark Tank India, IIT/IIM, tier 2 cities, D2C brands. 7) End with question people WANT to answer. 8) Include 3 to 5 hashtags as the final line of the SAME post string, right after the question, not as a separate item. 9) Never use hyphens or em dashes anywhere in the text, write plain sentences instead. 10) The JSON array must contain exactly 2 strings total, each one a complete standalone post including its own hashtags at the end. Do not return hashtags as their own array entry.
Return ONLY a valid JSON array of 2 strings. No markdown.`);const parsed=parseJSON(text);setPosts((parsed&&Array.isArray(parsed)&&parsed.length)?parsed.map(stripDashes):getFallback(topic,niche));setLoading(false);};
  return(<ToolCard title="Post Generator" icon="📝"><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TOPIC</div><input value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>e.key==="Enter"&&generate()} placeholder="e.g. AI replacing jobs, startup failure lessons, remote work" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><div style={{marginBottom:"14px"}}><NichePills niches={niches} active={niche} onSelect={setNiche}/></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TONE</div><div style={{marginBottom:"16px"}}><NichePills niches={tones} active={tone} onSelect={setTone}/></div><GenButton onClick={generate} loading={loading} label="✦ Generate LinkedIn Posts"/></GlassCard>
  {loading&&<Skeleton lines={2}/>}
  {!loading&&posts.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{posts.map((p,i)=><GlassCard key={i} style={{cursor:"pointer",borderLeft:"3px solid #0077b5"}} onClick={()=>{navigator.clipboard.writeText(p);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"10px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>Post {i+1}</div><div style={{fontSize:"11px",color:copied===i?C.success:"#60a5fa",fontWeight:"600"}}>{copied===i?"✓ Copied":"Copy"}</div></div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.85)",lineHeight:1.8,whiteSpace:"pre-line"}}>{p}</div><div style={{marginTop:"10px",fontSize:"10px",color:C.muted}}>{p.split(/\s+/).filter(Boolean).length} words</div></GlassCard>)}<GlassCard style={{borderLeft:"3px solid #0077b5"}}><div style={{fontSize:"10px",fontWeight:"700",color:"#60a5fa",marginBottom:"6px"}}>💼 LINKEDIN TIP</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.6)",lineHeight:1.6}}>First line is everything — it shows before "see more". Post Tue–Thu 8–10 AM IST. Engage with comments in first 60 mins. No links in post body — put in first comment.</div></GlassCard></div>}
  </ToolCard>);}

export function LinkedInHeadline(){
  const [role,setRole]=useState("");const [skills,setSkills]=useState("");const [niche,setNiche]=useState("general");const [headlines,setHeadlines]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["General","Tech","Startup","Marketing","Finance","Sales","Leadership","HR","Design","Product","AI","Consulting","Healthcare","Education","India"];
  const getFallback=(role,niche)=>{const pool=HL_FB[niche]||HL_FB.general;return pool.map(h=>filterBad(h.replace(/{role}/g,role||"Professional").replace(/{specialty}/g,skills||"my field").replace(/{topic}/g,skills||"my craft")));};
  const generate=async()=>{if(!role.trim())return;setLoading(true);setHeadlines([]);const text=await askGemini(`Write 5 LinkedIn headline options for: role="${filterBad(role)}" skills="${filterBad(skills)}" niche=${niche}. Max 220 chars each. No buzzwords like "passionate guru ninja rockstar". Sound human and specific. Include Indian context if relevant. Return ONLY a valid JSON array of 5 strings. No markdown.`);const parsed=parseJSON(text);setHeadlines((parsed&&Array.isArray(parsed)&&parsed.length)?parsed.map(stripDashes):getFallback(role,niche));setLoading(false);};
  return(<ToolCard title="Headline Writer" icon="✍️"><GlassCard style={{marginBottom:"16px"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"14px"}}><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>YOUR ROLE *</div><input value={role} onChange={e=>setRole(e.target.value)} placeholder="e.g. Product Manager, Founder" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>KEY SKILLS</div><input value={skills} onChange={e=>setSkills(e.target.value)} placeholder="e.g. AI, growth, SaaS, B2B" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><div style={{marginBottom:"16px"}}><NichePills niches={niches} active={niche} onSelect={setNiche}/></div><GenButton onClick={generate} loading={loading} label="✦ Generate Headlines"/></GlassCard>
  {loading&&<Skeleton lines={5}/>}
  {!loading&&headlines.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"8px"}}>{headlines.map((h,i)=><GlassCard key={i} style={{cursor:"pointer",padding:"14px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:"12px"}} onClick={()=>{navigator.clipboard.writeText(h);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{flex:1}}><div style={{fontSize:"13px",color:"rgba(255,255,255,0.85)",fontWeight:"600",lineHeight:1.5}}>{h}</div><div style={{marginTop:"4px",fontSize:"10px",color:h.length>220?C.danger:C.muted}}>{h.length}/220 chars</div></div><div style={{fontSize:"11px",color:copied===i?C.success:"#60a5fa",fontWeight:"600",flexShrink:0}}>{copied===i?"✓":"Copy"}</div></GlassCard>)}</div>}
  </ToolCard>);}

export function LinkedInAbout(){
  const [name,setName]=useState("");const [role,setRole]=useState("");const [topic,setTopic]=useState("");const [achievement,setAchievement]=useState("");const [abouts,setAbouts]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const getFallback=()=>["I've spent years obsessing over "+topic+".\n\nNot because it was required. Because I genuinely believe it's one of the most important skills right now.\n\nMy journey:\n▸ Started from scratch\n▸ "+achievement+"\n▸ Now focused on "+role+"\n\nIf you're working on "+topic+" or want to connect — let's talk.\n\n📩 Connect with me here on LinkedIn","The best thing that ever happened to my career? Failing at "+topic+" publicly.\n\nIt forced me to actually understand it instead of just talking about it.\n\nSince then:\n→ "+achievement+"\n→ Built something worth sharing\n→ Started sharing everything I learn\n\nI'm "+name+" — "+role+". Follow for the unfiltered version of building in "+topic+"."];
  const generate=async()=>{if(!role.trim())return;setLoading(true);setAbouts([]);const text=await askGemini(`Write 2 LinkedIn About sections for: name="${filterBad(name)}" role="${filterBad(role)}" expertise="${filterBad(topic)}" achievement="${filterBad(achievement)}". 200-400 words each. Start with a hook NOT "I am". Story: origin → journey → now → CTA. Use ▸ for bullets. End with email/DM CTA. Sound human, specific, like a real Indian professional. Return ONLY a valid JSON array of 2 strings. No markdown.`);const parsed=parseJSON(text);setAbouts((parsed&&Array.isArray(parsed)&&parsed.length)?parsed.map(stripDashes):getFallback());setLoading(false);};
  return(<ToolCard title="About Section Writer" icon="👤"><GlassCard style={{marginBottom:"16px"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"14px"}}><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>YOUR NAME</div><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Yash Agrawal" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>YOUR ROLE *</div><input value={role} onChange={e=>setRole(e.target.value)} placeholder="e.g. Founder, Product Manager" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>EXPERTISE</div><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. AI tools, SaaS, content creation" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>KEY ACHIEVEMENT</div><input value={achievement} onChange={e=>setAchievement(e.target.value)} placeholder="e.g. Built SocioMee, grew 10K users" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div></div><GenButton onClick={generate} loading={loading} label="✦ Generate About Section"/></GlassCard>
  {loading&&<Skeleton lines={2}/>}
  {!loading&&abouts.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{abouts.map((a,i)=><GlassCard key={i} style={{cursor:"pointer"}} onClick={()=>{navigator.clipboard.writeText(a);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"10px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>Version {i+1}</div><div style={{fontSize:"11px",color:copied===i?C.success:"#60a5fa",fontWeight:"600"}}>{copied===i?"✓ Copied":"Copy"}</div></div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.85)",lineHeight:1.8,whiteSpace:"pre-line"}}>{a}</div></GlassCard>)}</div>}
  </ToolCard>);}

export function LinkedInCarousel(){
  const [topic,setTopic]=useState("");const [niche,setNiche]=useState("general");const [carousels,setCarousels]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["General","Tech","Startup","Marketing","Finance","Sales","Leadership","HR","Design","Product","AI","India"];
  const getFallback=(topic)=>[{title:`5 ${topic} Mistakes That Kill Your Results`,slides:["Slide 1: The hook — surprising stat about "+topic,"Slide 2: Mistake #1 — Going too broad too fast","Slide 3: Mistake #2 — Ignoring the fundamentals","Slide 4: Mistake #3 — Copying without understanding","Slide 5: Mistake #4 — Optimizing before validating","Slide 6: Mistake #5 — Working alone when you don't have to","Slide 7: The fix — One simple framework for "+topic,"Slide 8: CTA — Save this + Follow for more"]},{title:`The ${topic} Framework That Changed Everything`,slides:["Slide 1: Before I knew this, I struggled with "+topic,"Slide 2: Step 1 — Understand the core principle","Slide 3: Step 2 — Start smaller than you think","Slide 4: Step 3 — Measure what actually matters","Slide 5: Step 4 — Iterate based on real data","Slide 6: Step 5 — Scale only what works","Slide 7: Results you can realistically expect","Slide 8: CTA — Which step are you on? Comment below"]}];
  const generate=async()=>{if(!topic.trim())return;setLoading(true);setCarousels([]);const text=await askGemini(`Generate 2 LinkedIn carousel ideas for: "${filterBad(topic)}" niche: ${niche}. Each has title (cover slide) and 8 slide descriptions. Cover must stop scroll — use numbers or strong promise. Last slide always CTA. Return ONLY a valid JSON array of 2 objects: [{"title":"title","slides":["slide 1","slide 2",...]}]. No markdown.`);const parsed=parseJSON(text);setCarousels((parsed&&Array.isArray(parsed)&&parsed.length)?parsed:getFallback(topic));setLoading(false);};
  return(<ToolCard title="Carousel Idea Generator" icon="🎠"><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TOPIC</div><input value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>e.key==="Enter"&&generate()} placeholder="e.g. productivity habits, AI tools, sales techniques" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><div style={{marginBottom:"16px"}}><NichePills niches={niches} active={niche} onSelect={setNiche}/></div><GenButton onClick={generate} loading={loading} label="✦ Generate Carousel Ideas"/></GlassCard>
  {loading&&<Skeleton lines={2}/>}
  {!loading&&carousels.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"16px"}}>{carousels.map((c,i)=><GlassCard key={i} style={{borderLeft:"3px solid #0077b5"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:"14px"}}><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",marginBottom:"4px"}}>Carousel {i+1}</div><div style={{fontSize:"15px",fontWeight:"800",color:"#60a5fa",lineHeight:1.4}}>{c.title}</div></div><button onClick={()=>{navigator.clipboard.writeText(`${c.title}\n\n${c.slides.map((s,j)=>`Slide ${j+1}: ${s}`).join("\n")}`);setCopied(i);setTimeout(()=>setCopied(null),2000);}} style={{padding:"6px 14px",borderRadius:"99px",border:"1px solid rgba(0,119,181,0.3)",background:"rgba(0,119,181,0.1)",color:copied===i?C.success:"#60a5fa",fontSize:"11px",fontWeight:"700",cursor:"pointer",fontFamily:"inherit"}}>{copied===i?"✓":"Copy All"}</button></div><div style={{display:"flex",flexDirection:"column",gap:"6px"}}>{c.slides?.map((slide,j)=><div key={j} style={{display:"flex",gap:"10px",alignItems:"flex-start",padding:"8px 10px",borderRadius:"8px",background:"rgba(255,255,255,0.03)"}}><div style={{width:"20px",height:"20px",borderRadius:"6px",background:"rgba(0,119,181,0.2)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"10px",fontWeight:"800",color:"#60a5fa",flexShrink:0}}>{j+1}</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.75)",lineHeight:1.5}}>{slide}</div></div>)}</div></GlassCard>)}<GlassCard style={{borderLeft:"3px solid #0077b5"}}><div style={{fontSize:"10px",fontWeight:"700",color:"#60a5fa",marginBottom:"6px"}}>🎠 CAROUSEL TIP</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.6)",lineHeight:1.6}}>LinkedIn carousels get 3x more reach. Cover slide is everything. Keep each slide to one idea. Last slide CTA should ask to follow or comment.</div></GlassCard></div>}
  </ToolCard>);}

export function LinkedInHashtags(){
  const [topic,setTopic]=useState("");const [niche,setNiche]=useState("general");const [count,setCount]=useState(10);const [tags,setTags]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(false);
  const niches=["General","Tech","Startup","Marketing","Finance","Sales","Leadership","HR","Design","Product","AI","India"];
  const FB_TAGS={tech:["#Technology","#Innovation","#AI","#TechLeadership","#FutureOfWork","#SoftwareEngineering","#ProductManagement","#StartupTech","#DigitalTransformation","#TechIndia","#BuildingInPublic","#SaaS","#MachineLearning","#DataScience","#CloudComputing","#DevOps","#TechTrends","#Automation","#OpenSource","#TechCommunity"],general:["#LinkedIn","#ProfessionalDevelopment","#Leadership","#CareerGrowth","#Networking","#PersonalBranding","#Mindset","#Productivity","#WorkCulture","#FutureOfWork","#Learning","#Growth","#Motivation","#Career","#India","#Business","#Success","#Innovation","#Community","#Mentorship"]};
  const getFallback=(topic,niche,count)=>{const pool=FB_TAGS[niche]||FB_TAGS.general;const tt=topic?[`#${topic.replace(/\s+/g,"")}`,`#${topic.replace(/\s+/g,"")}LinkedIn`]:[];return[...tt,...pool].slice(0,count);};
  const generate=async()=>{setLoading(true);setTags([]);const text=await askGemini(`Generate ${count} LinkedIn hashtags for: "${topic||niche}" niche: ${niche}. Mix broad and niche-specific. All start with #, CamelCase. Return ONLY a valid JSON array of ${count} strings.`);const parsed=parseJSON(text);setTags((parsed&&Array.isArray(parsed)&&parsed.length)?parsed.slice(0,count).map(stripDashes):getFallback(topic,niche,count));setLoading(false);};
  const copyAll=()=>{navigator.clipboard.writeText(tags.join(" "));setCopied(true);setTimeout(()=>setCopied(false),2000);};
  return(<ToolCard title="Hashtag Generator" icon="🏷️"><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>POST TOPIC</div><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. AI productivity, startup growth, leadership" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"16px",marginBottom:"16px"}}><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><NichePills niches={niches} active={niche} onSelect={setNiche}/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>COUNT: {count}</div><input type="range" min="5" max="20" value={count} onChange={e=>setCount(Number(e.target.value))} style={{width:"100%",accentColor:"#0077b5"}}/><div style={{display:"flex",justifyContent:"space-between",fontSize:"10px",color:C.muted,marginTop:"4px"}}><span>5</span><span>20</span></div></div></div><GenButton onClick={generate} loading={loading} label="✦ Generate Hashtags"/></GlassCard>
  {loading&&<Skeleton lines={1}/>}
  {!loading&&tags.length>0&&<GlassCard><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"12px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>{tags.length} HASHTAGS · Use 3-5 per post</div><button onClick={copyAll} style={{padding:"6px 16px",borderRadius:"99px",border:"1px solid rgba(0,119,181,0.3)",background:"rgba(0,119,181,0.1)",color:copied?C.success:"#60a5fa",fontSize:"11px",fontWeight:"700",cursor:"pointer",fontFamily:"inherit"}}>{copied?"✓ Copied":"Copy All"}</button></div><div style={{display:"flex",flexWrap:"wrap",gap:"6px"}}>{tags.map((tag,i)=><span key={i} onClick={()=>navigator.clipboard.writeText(tag)} style={{padding:"5px 12px",borderRadius:"99px",background:"rgba(0,119,181,0.1)",border:"1px solid rgba(0,119,181,0.25)",color:"#60a5fa",fontSize:"12px",fontWeight:"600",cursor:"pointer"}}>{tag}</span>)}</div></GlassCard>}
  </ToolCard>);}

export function LinkedInBestTime(){
  const [niche,setNiche]=useState("general");const [audience,setAudience]=useState("india");const [result,setResult]=useState(null);const [loading,setLoading]=useState(false);
  const niches=["general","tech","startup","marketing","finance","sales","leadership","hr","design","product","ai","consulting","healthcare","education","india"];
  const audiences=[{id:"india",label:"India (IST)"},{id:"global",label:"Global (EST)"},{id:"uk",label:"UK & Europe"},{id:"usa",label:"USA"},{id:"middle_east",label:"Middle East"},{id:"australia",label:"Australia"}];
  const analyze=async()=>{setLoading(true);setResult(null);const text=await askGemini(`Best times to post on LinkedIn for niche: "${niche}" audience: "${audience}". Return ONLY valid JSON: {"times":[{"time":"8:00 AM – 10:00 AM IST","reason":"reason","score":96,"day":"Tue–Thu"}],"best_days":["Tuesday"],"avoid":["Friday afternoon"],"tip":"specific LinkedIn tip","frequency":"X posts per week"} 3 time slots. Score out of 100.`);const parsed=parseJSON(text);setResult((parsed&&parsed.times)?parsed:(TIME_FB[audience]||TIME_FB.india));setLoading(false);};
  const scoreColor=s=>s>=90?"#34d399":s>=80?"#f59e0b":"#f87171";
  return(<ToolCard title="Best Time to Post" icon="⏰"><GlassCard style={{marginBottom:"16px"}}><div style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><NichePills niches={niches} active={niche} onSelect={setNiche}/></div><div style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>AUDIENCE</div><div style={{display:"flex",flexWrap:"wrap",gap:"6px"}}>{audiences.map(a=><button key={a.id} onClick={()=>setAudience(a.id)} style={{padding:"5px 14px",borderRadius:"99px",border:`1.5px solid ${audience===a.id?"rgba(0,119,181,0.7)":"rgba(255,255,255,0.1)"}`,background:audience===a.id?"rgba(0,119,181,0.15)":"transparent",color:audience===a.id?"#60a5fa":"rgba(255,255,255,0.5)",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{a.label}</button>)}</div></div><GenButton onClick={analyze} loading={loading} label="✦ Analyze Best Times"/></GlassCard>
  {loading&&<Skeleton lines={3}/>}
  {!loading&&result&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}><GlassCard><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"12px"}}>🕐 Best Times</div>{result.times?.map((t,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:"12px",padding:"10px 14px",borderRadius:"12px",background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.06)",marginBottom:"8px"}}><div style={{fontSize:"20px",fontWeight:"900",color:scoreColor(t.score),minWidth:"36px",textAlign:"center"}}>{t.score}</div><div style={{flex:1}}><div style={{fontSize:"13px",fontWeight:"700",color:"#fff",marginBottom:"2px"}}>{t.time} <span style={{fontSize:"10px",color:C.muted}}>· {t.day}</span></div><div style={{fontSize:"11px",color:C.muted}}>{t.reason}</div></div><div style={{width:"5px",height:"36px",borderRadius:"99px",background:scoreColor(t.score),opacity:0.7}}/></div>)}</GlassCard><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px"}}><GlassCard><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"10px"}}>✅ Best Days</div>{result.best_days?.map((d,i)=><div key={i} style={{fontSize:"13px",color:"#34d399",fontWeight:"600",marginBottom:"4px"}}>• {d}</div>)}</GlassCard><GlassCard><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"10px"}}>❌ Avoid</div>{result.avoid?.map((d,i)=><div key={i} style={{fontSize:"11px",color:"#f87171",fontWeight:"600",marginBottom:"4px"}}>• {d}</div>)}</GlassCard></div><GlassCard style={{borderLeft:"3px solid #0077b5"}}><div style={{fontSize:"10px",fontWeight:"700",color:"#60a5fa",marginBottom:"6px"}}>💼 PRO TIP</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.8)",lineHeight:1.6,marginBottom:"8px"}}>{result.tip}</div><div style={{fontSize:"12px",color:C.muted}}>📅 <span style={{color:"#60a5fa",fontWeight:"700"}}>{result.frequency}</span></div></GlassCard></div>}
  </ToolCard>);}
