/* eslint-disable */
import React, { useState, useRef, useEffect } from "react";

const s = {
  wrap: { fontFamily:"Poppins,sans-serif", color:"#fff", maxWidth:"560px", margin:"0 auto" },
  label: { fontSize:"12px", fontWeight:"600", color:"rgba(255,255,255,0.5)", marginBottom:"6px", display:"block", letterSpacing:"0.5px", textTransform:"uppercase" },
  input: { width:"100%", background:"rgba(255,255,255,0.05)", border:"1px solid rgba(255,255,255,0.1)", borderRadius:"10px", padding:"12px 14px", color:"#fff", fontSize:"13px", fontFamily:"Poppins,sans-serif", outline:"none", marginBottom:"16px" },
  btn: { width:"100%", padding:"13px", borderRadius:"10px", border:"1px solid rgba(255,255,255,0.12)", background:"rgba(255,255,255,0.07)", color:"#fff", fontSize:"13px", fontWeight:"700", cursor:"pointer", fontFamily:"Poppins,sans-serif", transition:"all 0.2s" },
  preview: { display:"flex", flexDirection:"column", alignItems:"center", gap:"16px", marginTop:"28px", padding:"28px", background:"rgba(255,255,255,0.03)", border:"1px solid rgba(255,255,255,0.08)", borderRadius:"16px" },
};

export default function QRGenerator({ user }) {
  const [url, setUrl] = useState("");
  const [label, setLabel] = useState("");
  const [size, setSize] = useState(256);
  const [generated, setGenerated] = useState(false);
  const [qrDataUrl, setQrDataUrl] = useState("");
  const canvasRef = useRef(null);

  const generateQR = async () => {
    if (!url.trim()) return;
    try {
      // Use QRServer API - no library needed
      const encoded = encodeURIComponent(url.trim());
      const imgUrl = `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&data=${encoded}&bgcolor=0a0a0a&color=ffffff&margin=10`;
      setQrDataUrl(imgUrl);
      setGenerated(true);
    } catch(e) {
      alert("Failed to generate QR code.");
    }
  };

  const download = () => {
    const a = document.createElement("a");
    a.href = qrDataUrl;
    a.download = `qr-${label || "sociomee"}.png`;
    a.click();
  };

  return (
    <div style={s.wrap}>
      <div style={{marginBottom:"24px"}}>
        <div style={{fontSize:"18px",fontWeight:"800",color:"#fff",marginBottom:"4px"}}>QR Code Generator</div>
        <div style={{fontSize:"13px",color:"rgba(255,255,255,0.4)"}}>Turn any link into a scannable QR code. Download and share anywhere.</div>
      </div>

      <label style={s.label}>URL or Text</label>
      <input
        style={s.input}
        placeholder="https://sociomeeai.com or any link..."
        value={url}
        onChange={e=>setUrl(e.target.value)}
        onKeyDown={e=>e.key==="Enter"&&generateQR()}
      />

      <label style={s.label}>Label (for filename)</label>
      <input
        style={s.input}
        placeholder="e.g. my-instagram-link"
        value={label}
        onChange={e=>setLabel(e.target.value)}
      />

      <label style={s.label}>Size</label>
      <div style={{display:"flex",gap:"8px",marginBottom:"16px"}}>
        {[128,256,512].map(sz=>(
          <button key={sz} onClick={()=>setSize(sz)} style={{flex:1,padding:"8px",borderRadius:"8px",border:`1px solid ${size===sz?"rgba(255,255,255,0.4)":"rgba(255,255,255,0.08)"}`,background:size===sz?"rgba(255,255,255,0.1)":"rgba(255,255,255,0.02)",color:size===sz?"#fff":"rgba(255,255,255,0.4)",fontSize:"12px",fontWeight:"700",cursor:"pointer",fontFamily:"Poppins,sans-serif"}}>
            {sz}×{sz}
          </button>
        ))}
      </div>

      <button style={s.btn} onClick={generateQR} disabled={!url.trim()}>
        Generate QR Code
      </button>

      {generated && qrDataUrl && (
        <div style={s.preview}>
          <img src={qrDataUrl} alt="QR Code" style={{width:size>256?256:size,height:size>256?256:size,borderRadius:"8px",display:"block"}}/>
          <div style={{fontSize:"12px",color:"rgba(255,255,255,0.4)",textAlign:"center",wordBreak:"break-all",maxWidth:"300px"}}>{url}</div>
          <button onClick={download} style={{...s.btn,width:"auto",padding:"10px 28px"}}>
            Download PNG
          </button>
          <div style={{fontSize:"11px",color:"rgba(255,255,255,0.25)"}}>Generated by SocioMee AI</div>
        </div>
      )}
    </div>
  );
}
