import { useState } from "react";
const C={red:"#b92b27",glass:"rgba(255,255,255,0.04)",hairline:"rgba(255,255,255,0.08)",ink:"rgba(255,255,255,0.9)",muted:"rgba(255,255,255,0.4)",success:"#34d399",danger:"#f87171"};
const AI="https://sociomeeai.com/api/ai/generate";
let lastCall=0;
const BAD_WORDS=['fuck','shit','bitch','bastard','asshole','nigger','faggot','chutiya','madarchod','bhenchod','randi','harami','gandu','motherfucker','child porn','cocaine','heroin','meth','jihad','massacre','genocide','bomb','suicide','how to kill','terrorist','explosive','drug deal','buy guns','illegal weapons','human trafficking','rape','molest','hack into','ransomware','darkweb','money laundering','assassination'];
function filterBad(t){let s=t;BAD_WORDS.forEach(w=>{const re=new RegExp('\\b'+w+'\\b','gi');s=s.replace(re,'*'.repeat(w.length));});return s;}
async function askGemini(prompt){const now=Date.now();if(now-lastCall<3000)await new Promise(r=>setTimeout(r,3000-(now-lastCall)));lastCall=Date.now();try{const r=await fetch(AI,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[{role:"user",content:prompt}],cost:2})});if(!r.ok)return"";const d=await r.json();if(d.credit_status)window.dispatchEvent(new CustomEvent("sociomee-credits-updated",{detail:d.credit_status}));return d.content?.[0]?.text||"";}catch{return"";}}
function parseJSON(text){try{const c=text.replace(/```json|```/g,"").trim();const m=c.match(/(\[[\s\S]*\]|\{[\s\S]*\})/);return JSON.parse(m?m[1]:c);}catch{return null;}}
function stripDashes(s){return typeof s==="string"?s.replace(/[\u2013\u2014-]/g," "):s;}
function ToolCard({title,icon,children}){return <div style={{maxWidth:"700px",margin:"0 auto",padding:"20px 16px"}}><div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"20px"}}><span style={{fontSize:"20px"}}>{icon}</span><h2 style={{fontSize:"18px",fontWeight:"900",color:"#fff",margin:0}}>{title}</h2></div>{children}</div>;}
function GlassCard({children,style={}}){return <div style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"16px",padding:"20px",...style}}>{children}</div>;}
function GenButton({onClick,loading,label="✦ Generate"}){return <button onClick={onClick} disabled={loading} style={{width:"100%",padding:"14px",borderRadius:"99px",border:"1.5px solid rgba(185,43,39,0.6)",background:loading?"rgba(185,43,39,0.05)":"rgba(185,43,39,0.15)",backdropFilter:"blur(16px)",color:"#fff",fontWeight:"800",fontSize:"14px",cursor:loading?"not-allowed":"pointer",fontFamily:"inherit",boxShadow:"none",transition:"all 0.3s",opacity:loading?0.6:1}}>{loading?"Generating…":label}</button>;}
function NichePills({niches,active,onSelect}){return <div style={{display:"flex",gap:"6px",flexWrap:"wrap"}}>{niches.map(n=>{const isActive=active===n.toLowerCase();return <button key={n} onClick={()=>onSelect(n.toLowerCase())} style={{padding:"5px 12px",borderRadius:"99px",border:`1.5px solid ${isActive?"rgba(185,43,39,0.7)":"rgba(255,255,255,0.1)"}`,background:isActive?"rgba(185,43,39,0.15)":"transparent",color:isActive?"#e07875":"rgba(255,255,255,0.5)",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{n}</button>;})}</div>;}
function Skeleton({lines=3}){return <div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{Array(lines).fill(0).map((_,i)=><GlassCard key={i}><div style={{display:"flex",flexDirection:"column",gap:"10px"}}><div style={{height:"12px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"40%"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"70%"}}/></div></GlassCard>)}<style>{`@keyframes shimmer{to{background-position:-200% 0}}`}</style></div>;}

const ANSWER_FB={general:["Honestly most people get this wrong because they focus on the exciting parts and skip the boring fundamentals.\n\nHere is what actually worked for me:\n\nStart small. Measure what happens. Adjust based on real data, not opinions.\n\nThe people who succeed at this are not the most talented. They are the most consistent.\n\nI wrote a more detailed breakdown here: sociomeeai.com"],creator:["Most creators quit right before things start working. The first 90 days are brutal because you are posting into silence.\n\nWhat changed things for me: picking one platform and one format, then showing up daily even when the numbers looked embarrassing.\n\nConsistency beats talent in this game almost every time.\n\nI wrote a more detailed breakdown here: sociomeeai.com"],business:["The businesses that win here are not the ones with the biggest budget. They are the ones who actually listen to what customers are saying and adjust fast.\n\nMost companies collect feedback and ignore it. The ones who act on it compound their advantage every quarter.\n\nI wrote a more detailed breakdown here: sociomeeai.com"]};

export function QuoraAnswer(){
  const [question,setQuestion]=useState("");const [niche,setNiche]=useState("general");const [tone,setTone]=useState("direct opinion");const [language,setLanguage]=useState("english");const [answers,setAnswers]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["General","Creator","Business","Tech","Startup","Marketing","Finance","Career","India","Health","Relationships","Education"];
  const tones=["Direct Opinion","Personal Story","Contrarian Take","Educational","Data-driven"];
  const languages=["Hinglish","Hindi","English","Marathi","Tamil","Bengali"];
  const getFallback=(niche)=>{const pool=ANSWER_FB[niche]||ANSWER_FB.general;return [...pool];};
  const generate=async()=>{if(!question.trim())return;setLoading(true);setAnswers([]);const text=await askGemini(`Write 2 Quora answers in ${language} language for the question: "${filterBad(question)}" niche: ${niche} tone: ${tone}.
RULES: 1) Actually answer the question that was asked, directly and practically. Do not argue that the question's premise or goal is wrong. NEVER start with "great question" or "that's a good question". 2) 200 to 350 words. 3) Two to four short paragraphs, conversational, like a real person typing, not a listicle. 4) No bullet points, no numbered lists — prose only. 5) Include one specific practical tip or personal observation, something the reader can actually use. 6) Do not include any link, URL, or mention of any product or website anywhere in the answer. 7) No hyphens or em dashes anywhere in the text. 8) Sound human, not AI generated, plain everyday words. 9) Write the entire answer in ${language}.
Return ONLY a valid JSON array of 2 strings. No markdown.`);const parsed=parseJSON(text);setAnswers((parsed&&Array.isArray(parsed)&&parsed.length)?parsed:getFallback(niche));setLoading(false);};
  return(<ToolCard title="Answer Generator" icon="❓"><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>QUORA QUESTION</div><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==="Enter"&&generate()} placeholder="e.g. How do I grow on YouTube with zero subscribers?" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>LANGUAGE</div><div style={{marginBottom:"14px"}}><NichePills niches={languages} active={language} onSelect={setLanguage}/></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><div style={{marginBottom:"14px"}}><NichePills niches={niches} active={niche} onSelect={setNiche}/></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TONE</div><div style={{marginBottom:"16px"}}><NichePills niches={tones} active={tone} onSelect={setTone}/></div><GenButton onClick={generate} loading={loading} label="✦ Generate Quora Answers"/></GlassCard>
  {loading&&<Skeleton lines={2}/>}
  {!loading&&answers.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{answers.map((a,i)=><GlassCard key={i} style={{cursor:"pointer",borderLeft:"3px solid #b92b27"}} onClick={()=>{navigator.clipboard.writeText(a);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"10px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>Answer {i+1}</div><div style={{fontSize:"11px",color:copied===i?C.success:"#e07875",fontWeight:"600"}}>{copied===i?"✓ Copied":"Copy"}</div></div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.85)",lineHeight:1.8,whiteSpace:"pre-line"}}>{a}</div><div style={{marginTop:"10px",fontSize:"10px",color:C.muted}}>{a.split(/\s+/).filter(Boolean).length} words</div></GlassCard>)}<GlassCard style={{borderLeft:"3px solid #b92b27"}}><div style={{fontSize:"10px",fontWeight:"700",color:"#e07875",marginBottom:"6px"}}>❓ QUORA TIP</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.6)",lineHeight:1.6}}>Target questions with 50K to 500K followers but fewer than 20 answers. Build credibility first by answering genuinely before linking anywhere. Answers rank on Google for years.</div></GlassCard></div>}
  </ToolCard>);}

export function QuoraQuestionFinder(){
  const [niche,setNiche]=useState("general");const [questions,setQuestions]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["General","Creator","Business","Tech","Startup","Marketing","Finance","Career","India","Health","Relationships","Education"];
  const getFallback=()=>["What is the best AI tool for content creators in 2026?","How do I grow my YouTube channel with zero budget?","What is the biggest mistake new creators make?","How much can a creator realistically earn in the first year?"];
  const generate=async()=>{setLoading(true);setQuestions([]);const text=await askGemini(`Suggest 6 real, high search volume Quora questions in the niche: "${niche}" that a content creator or business could genuinely answer to build authority and drive traffic. Questions should sound like actual things people search, natural phrasing. Return ONLY a valid JSON array of 6 strings. No markdown.`);const parsed=parseJSON(text);setQuestions((parsed&&Array.isArray(parsed)&&parsed.length)?parsed:getFallback());setLoading(false);};
  return(<ToolCard title="Question Finder" icon="🔍"><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><div style={{marginBottom:"16px"}}><NichePills niches={niches} active={niche} onSelect={setNiche}/></div><GenButton onClick={generate} loading={loading} label="✦ Find Questions"/></GlassCard>
  {loading&&<Skeleton lines={3}/>}
  {!loading&&questions.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"8px"}}>{questions.map((q,i)=><GlassCard key={i} style={{cursor:"pointer",padding:"14px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:"12px"}} onClick={()=>{navigator.clipboard.writeText(q);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{flex:1,fontSize:"13px",color:"rgba(255,255,255,0.85)",fontWeight:"600",lineHeight:1.5}}>{q}</div><div style={{fontSize:"11px",color:copied===i?C.success:"#e07875",fontWeight:"600",flexShrink:0}}>{copied===i?"✓":"Copy"}</div></GlassCard>)}</div>}
  </ToolCard>);}

export function QuoraHook(){
  const [topic,setTopic]=useState("");const [hooks,setHooks]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const getFallback=(topic)=>[`Most people get ${topic} completely wrong, and it costs them years.`,`I used to believe the opposite of this about ${topic}, until I actually tried it.`,`Nobody talks about the real reason ${topic} works, so here it is.`];
  const generate=async()=>{if(!topic.trim())return;setLoading(true);setHooks([]);const text=await askGemini(`Write 5 strong opening lines for a Quora answer about: "${filterBad(topic)}". Each should be a contrarian take, surprising fact, or bold personal claim that makes someone want to keep reading. No hyphens or em dashes. Sound human. Return ONLY a valid JSON array of 5 strings. No markdown.`);const parsed=parseJSON(text);setHooks((parsed&&Array.isArray(parsed)&&parsed.length)?parsed:getFallback(topic));setLoading(false);};
  return(<ToolCard title="Hook Generator" icon="⚡"><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TOPIC OR QUESTION</div><input value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>e.key==="Enter"&&generate()} placeholder="e.g. growing on YouTube, brand deals, AI tools" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"16px"}}/><GenButton onClick={generate} loading={loading} label="✦ Generate Hooks"/></GlassCard>
  {loading&&<Skeleton lines={5}/>}
  {!loading&&hooks.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"8px"}}>{hooks.map((h,i)=><GlassCard key={i} style={{cursor:"pointer",padding:"14px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:"12px"}} onClick={()=>{navigator.clipboard.writeText(h);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{flex:1,fontSize:"13px",color:"rgba(255,255,255,0.85)",fontWeight:"600",lineHeight:1.5}}>{h}</div><div style={{fontSize:"11px",color:copied===i?C.success:"#e07875",fontWeight:"600",flexShrink:0}}>{copied===i?"✓":"Copy"}</div></GlassCard>)}</div>}
  </ToolCard>);}
