import { useState } from "react";
const C={red:"rgba(255,255,255,0.8)",glass:"rgba(255,255,255,0.04)",hairline:"rgba(255,255,255,0.08)",ink:"rgba(255,255,255,0.9)",muted:"rgba(255,255,255,0.4)",success:"#34d399",danger:"#f87171"};
const AI="https://sociomeeai.com/api/ai/generate";
let lastCall=0;
const BAD_WORDS=['fuck','shit','bitch','bastard','asshole','nigger','faggot','chutiya','madarchod','bhenchod','randi','harami','gandu','motherfucker','child porn','cocaine','heroin','meth','jihad','massacre','genocide','bomb','suicide','how to kill','terrorist','explosive','drug deal','buy guns','illegal weapons','human trafficking','rape','molest','hack into','ransomware','darkweb','money laundering','assassination'];
function filterBad(t){let s=t;BAD_WORDS.forEach(w=>{const re=new RegExp('\\b'+w+'\\b','gi');s=s.replace(re,'*'.repeat(w.length));});return s;}
async function askGemini(prompt){const now=Date.now();if(now-lastCall<3000)await new Promise(r=>setTimeout(r,3000-(now-lastCall)));lastCall=Date.now();try{const r=await fetch(AI,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[{role:"user",content:prompt}],cost:2})});if(!r.ok)return"";const d=await r.json();if(d.credit_status)window.dispatchEvent(new CustomEvent("sociomee-credits-updated",{detail:d.credit_status}));return d.content?.[0]?.text||"";}catch{return"";}}
function parseJSON(text){try{const c=text.replace(/```json|```/g,"").trim();const m=c.match(/(\[[\s\S]*\]|\{[\s\S]*\})/);return JSON.parse(m?m[1]:c);}catch{return null;}}
function stripDashes(s){return typeof s==="string"?s.replace(/[\u2013\u2014-]/g," "):s;}
function ToolCard({title,icon,children}){return <div style={{maxWidth:"700px",margin:"0 auto",padding:"40px 16px",display:"flex",flexDirection:"column",justifyContent:"center",minHeight:"calc(100vh - 200px)"}}><div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"20px"}}><span style={{fontSize:"20px"}}>{icon}</span><h2 style={{fontSize:"18px",fontWeight:"900",color:"#fff",margin:0}}>{title}</h2></div>{children}</div>;}
function GlassCard({children,style={}}){return <div style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"16px",padding:"20px",...style}}>{children}</div>;}
function GenButton({onClick,loading,label="Generate"}){return <button onClick={onClick} disabled={loading} style={{width:"100%",padding:"14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.25)",background:loading?"rgba(255,255,255,0.03)":"rgba(255,255,255,0.08)",backdropFilter:"blur(16px)",color:"#fff",fontWeight:"800",fontSize:"14px",cursor:loading?"not-allowed":"pointer",fontFamily:"inherit",boxShadow:"none",transition:"all 0.3s",opacity:loading?0.6:1}}>{loading?"Generating…":label}</button>;}
function NichePills({niches,active,onSelect}){return <div style={{display:"flex",gap:"6px",flexWrap:"wrap"}}>{niches.map(n=>{const isActive=active===n.toLowerCase();return <button key={n} onClick={()=>onSelect(n.toLowerCase())} style={{padding:"5px 12px",borderRadius:"99px",border:`1.5px solid ${isActive?"rgba(255,255,255,0.25)":"rgba(255,255,255,0.1)"}`,background:isActive?"rgba(255,255,255,0.08)":"transparent",color:isActive?"rgba(255,255,255,0.6)":"rgba(255,255,255,0.5)",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{n}</button>;})}</div>;}
function Skeleton({lines=3}){return <div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{Array(lines).fill(0).map((_,i)=><GlassCard key={i}><div style={{display:"flex",flexDirection:"column",gap:"10px"}}><div style={{height:"12px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"40%"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"70%"}}/></div></GlassCard>)}<style>{`@keyframes shimmer{to{background-position:-200% 0}}`}</style></div>;}

const ANSWER_FB={general:["Honestly most people get this wrong because they focus on the exciting parts and skip the boring fundamentals.\n\nHere is what actually worked for me:\n\nStart small. Measure what happens. Adjust based on real data, not opinions.\n\nThe people who succeed at this are not the most talented. They are the most consistent.\n\nI wrote a more detailed breakdown here: sociomeeai.com"],creator:["Most creators quit right before things start working. The first 90 days are brutal because you are posting into silence.\n\nWhat changed things for me: picking one platform and one format, then showing up daily even when the numbers looked embarrassing.\n\nConsistency beats talent in this game almost every time.\n\nI wrote a more detailed breakdown here: sociomeeai.com"],business:["The businesses that win here are not the ones with the biggest budget. They are the ones who actually listen to what customers are saying and adjust fast.\n\nMost companies collect feedback and ignore it. The ones who act on it compound their advantage every quarter.\n\nI wrote a more detailed breakdown here: sociomeeai.com"]};

export function QuoraAnswer(){
  const [question,setQuestion]=useState("");const [niche,setNiche]=useState("general");const [tone,setTone]=useState("direct opinion");const [language,setLanguage]=useState("english");const [answers,setAnswers]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["General","Creator","Business","Tech","Startup","Marketing","Finance","Career","India","Health","Relationships","Education"];
  const tones=["Direct Opinion","Personal Story","Contrarian Take","Educational","Data-driven"];
  const languages=["Hinglish","Hindi","English","Marathi","Tamil","Bengali"];
  const getFallback=(niche)=>{const pool=ANSWER_FB[niche]||ANSWER_FB.general;return [...pool];};
  const generate=async()=>{if(!question.trim())return;setLoading(true);setAnswers([]);const text=await askGemini(`Write 2 Quora answers in ${language} language for the question: "${filterBad(question)}" niche: ${niche} tone: ${tone}.
RULES: 1) Actually answer the question that was asked, directly and practically. Do not argue that the question's premise or goal is wrong. NEVER start with "great question" or "that's a good question". 2) 200 to 350 words. 3) Two to four short paragraphs, conversational, like a real person typing, not a listicle. 4) No bullet points, no numbered lists — prose only. 5) Include one specific practical tip or personal observation, something the reader can actually use. 6) Do not include any link, URL, or mention of any product or website anywhere in the answer. 7) No hyphens or em dashes anywhere in the text. 8) Sound human, not AI generated, plain everyday words. 9) Write the entire answer in ${language}.
Return ONLY a valid JSON array of 2 strings. No markdown.`);const parsed=parseJSON(text);setAnswers((parsed&&Array.isArray(parsed)&&parsed.length)?parsed:getFallback(niche));setLoading(false);};
  return(<ToolCard title="Answer Generator" icon=""><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>QUORA QUESTION</div><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==="Enter"&&generate()} placeholder="e.g. How do I grow on YouTube with zero subscribers?" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>LANGUAGE</div><div style={{marginBottom:"14px"}}><NichePills niches={languages} active={language} onSelect={setLanguage}/></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><div style={{marginBottom:"14px"}}><NichePills niches={niches} active={niche} onSelect={setNiche}/></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TONE</div><div style={{marginBottom:"16px"}}><NichePills niches={tones} active={tone} onSelect={setTone}/></div><GenButton onClick={generate} loading={loading} label="Generate Quora Answers"/></GlassCard>
  {loading&&<Skeleton lines={2}/>}
  {!loading&&answers.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{answers.map((a,i)=><GlassCard key={i} style={{cursor:"pointer",borderLeft:"3px solid rgba(255,255,255,0.8)"}} onClick={()=>{navigator.clipboard.writeText(a);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"10px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>Answer {i+1}</div><div style={{fontSize:"11px",color:copied===i?C.success:"rgba(255,255,255,0.6)",fontWeight:"600"}}>{copied===i?"✓ Copied":"Copy"}</div></div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.85)",lineHeight:1.8,whiteSpace:"pre-line"}}>{a}</div><div style={{marginTop:"10px",fontSize:"10px",color:C.muted}}>{a.split(/\s+/).filter(Boolean).length} words</div></GlassCard>)}<GlassCard style={{borderLeft:"3px solid rgba(255,255,255,0.8)"}}><div style={{fontSize:"10px",fontWeight:"700",color:"rgba(255,255,255,0.6)",marginBottom:"6px"}}>QUORA TIP</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.6)",lineHeight:1.6}}>Target questions with 50K to 500K followers but fewer than 20 answers. Build credibility first by answering genuinely before linking anywhere. Answers rank on Google for years.</div></GlassCard></div>}
  </ToolCard>);}

export function QuoraQuestionFinder(){
  const [niche,setNiche]=useState("general");const [questions,setQuestions]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["General","Creator","Business","Tech","Startup","Marketing","Finance","Career","India","Health","Relationships","Education"];
  const getFallback=()=>["What is the best AI tool for content creators in 2026?","How do I grow my YouTube channel with zero budget?","What is the biggest mistake new creators make?","How much can a creator realistically earn in the first year?"];
  const generate=async()=>{setLoading(true);setQuestions([]);const text=await askGemini(`Suggest 6 real, high search volume Quora questions in the niche: "${niche}" that a content creator or business could genuinely answer to build authority and drive traffic. Questions should sound like actual things people search, natural phrasing. Return ONLY a valid JSON array of 6 strings. No markdown.`);const parsed=parseJSON(text);setQuestions((parsed&&Array.isArray(parsed)&&parsed.length)?parsed:getFallback());setLoading(false);};
  return(<ToolCard title="Question Finder" icon=""><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><div style={{marginBottom:"16px"}}><NichePills niches={niches} active={niche} onSelect={setNiche}/></div><GenButton onClick={generate} loading={loading} label="Find Questions"/></GlassCard>
  {loading&&<Skeleton lines={3}/>}
  {!loading&&questions.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"8px"}}>{questions.map((q,i)=><GlassCard key={i} style={{cursor:"pointer",padding:"14px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:"12px"}} onClick={()=>{navigator.clipboard.writeText(q);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{flex:1,fontSize:"13px",color:"rgba(255,255,255,0.85)",fontWeight:"600",lineHeight:1.5}}>{q}</div><div style={{fontSize:"11px",color:copied===i?C.success:"rgba(255,255,255,0.6)",fontWeight:"600",flexShrink:0}}>{copied===i?"✓":"Copy"}</div></GlassCard>)}</div>}
  </ToolCard>);}

export function QuoraHook(){
  const [topic,setTopic]=useState("");const [hooks,setHooks]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const getFallback=(topic)=>[`Most people get ${topic} completely wrong, and it costs them years.`,`I used to believe the opposite of this about ${topic}, until I actually tried it.`,`Nobody talks about the real reason ${topic} works, so here it is.`];
  const generate=async()=>{if(!topic.trim())return;setLoading(true);setHooks([]);const text=await askGemini(`Write 5 strong opening lines for a Quora answer about: "${filterBad(topic)}". Each should be a contrarian take, surprising fact, or bold personal claim that makes someone want to keep reading. No hyphens or em dashes. Sound human. Return ONLY a valid JSON array of 5 strings. No markdown.`);const parsed=parseJSON(text);setHooks((parsed&&Array.isArray(parsed)&&parsed.length)?parsed:getFallback(topic));setLoading(false);};
  return(<ToolCard title="Hook Generator" icon=""><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TOPIC OR QUESTION</div><input value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>e.key==="Enter"&&generate()} placeholder="e.g. growing on YouTube, brand deals, AI tools" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"16px"}}/><GenButton onClick={generate} loading={loading} label="Generate Hooks"/></GlassCard>
  {loading&&<Skeleton lines={5}/>}
  {!loading&&hooks.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"8px"}}>{hooks.map((h,i)=><GlassCard key={i} style={{cursor:"pointer",padding:"14px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:"12px"}} onClick={()=>{navigator.clipboard.writeText(h);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{flex:1,fontSize:"13px",color:"rgba(255,255,255,0.85)",fontWeight:"600",lineHeight:1.5}}>{h}</div><div style={{fontSize:"11px",color:copied===i?C.success:"rgba(255,255,255,0.6)",fontWeight:"600",flexShrink:0}}>{copied===i?"✓":"Copy"}</div></GlassCard>)}</div>}
  </ToolCard>);}

export function QuoraSpaceFinder(){
  const [niche,setNiche]=useState("");const [spaces,setSpaces]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["General","Creator","Business","Tech","Startup","Marketing","Finance","Career","India","Health","Relationships","Education","Fitness","Food","Travel","Science","Politics","Sports","Parenting","Self Improvement"];
  const generate=async()=>{if(!niche.trim())return;setLoading(true);setSpaces([]);const text=await askGemini(`List 8 real Quora Spaces that a creator or expert in "${filterBad(niche)}" should join and post in to build authority and get traffic. For each space include: name, estimated followers range, why it's good for this niche, and best type of content to post there. Return ONLY a valid JSON array of 8 objects: [{"name":"Space Name","followers":"50K-100K","why":"reason","best_content":"what to post"}]. No markdown.`);const parsed=parseJSON(text);setSpaces(parsed&&Array.isArray(parsed)&&parsed.length?parsed:[]);setLoading(false);};
  return(<ToolCard title="Space Finder" icon=""><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>YOUR NICHE</div><div style={{marginBottom:"14px"}}><NichePills niches={niches} active={niche} onSelect={setNiche}/></div><input value={niche} onChange={e=>setNiche(e.target.value)} placeholder="Or type your niche..." style={{width:"100%",padding:"10px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><GenButton onClick={generate} loading={loading} label="Find Quora Spaces"/></GlassCard>
  {loading&&<Skeleton lines={4}/>}
  {!loading&&spaces.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"10px"}}>{spaces.map((s,i)=><GlassCard key={i} style={{cursor:"pointer"}} onClick={()=>{navigator.clipboard.writeText(s.name);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:"8px"}}><div style={{flex:1}}><div style={{fontSize:"14px",fontWeight:"800",color:"#fff",marginBottom:"2px"}}>{s.name}</div><div style={{fontSize:"11px",color:C.muted}}>{s.followers} followers</div></div><div style={{fontSize:"11px",color:copied===i?C.success:"rgba(255,255,255,0.5)",fontWeight:"600",flexShrink:0}}>{copied===i?"✓ Copied":"Copy"}</div></div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.7)",lineHeight:1.6,marginBottom:"6px"}}>{s.why}</div><div style={{padding:"8px 12px",borderRadius:"8px",background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.06)"}}><div style={{fontSize:"10px",fontWeight:"700",color:C.muted,textTransform:"uppercase",marginBottom:"3px"}}>Best Content</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.6)"}}>{s.best_content}</div></div></GlassCard>)}</div>}
  </ToolCard>);}

export function QuoraProfileBio(){
  const [name,setName]=useState("");const [role,setRole]=useState("");const [expertise,setExpertise]=useState("");const [achievement,setAchievement]=useState("");const [bios,setBios]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const generate=async()=>{if(!role.trim())return;setLoading(true);setBios([]);const text=await askGemini(`Write 3 Quora profile bio options for: name="${filterBad(name)}" role="${filterBad(role)}" expertise="${filterBad(expertise)}" achievement="${filterBad(achievement)}". Each bio should be 60 to 100 words. Start with the role or expertise, not the name. Sound credible and human, like a real expert. Include a subtle hook that makes readers want to follow. No hyphens or em dashes. Indian context where relevant. Return ONLY a valid JSON array of 3 strings. No markdown.`);const parsed=parseJSON(text);setBios(parsed&&Array.isArray(parsed)&&parsed.length?parsed:[]);setLoading(false);};
  return(<ToolCard title="Profile Bio Writer" icon=""><GlassCard style={{marginBottom:"16px"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"14px"}}><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>YOUR NAME</div><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Yash Agrawal" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>YOUR ROLE</div><input value={role} onChange={e=>setRole(e.target.value)} placeholder="e.g. Founder, Developer" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>EXPERTISE</div><input value={expertise} onChange={e=>setExpertise(e.target.value)} placeholder="e.g. AI tools, SaaS, content" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>KEY ACHIEVEMENT</div><input value={achievement} onChange={e=>setAchievement(e.target.value)} placeholder="e.g. Built SocioMee, 10K users" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div></div><GenButton onClick={generate} loading={loading} label="Write Profile Bio"/></GlassCard>
  {loading&&<Skeleton lines={3}/>}
  {!loading&&bios.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"10px"}}>{bios.map((b,i)=><GlassCard key={i} style={{cursor:"pointer"}} onClick={()=>{navigator.clipboard.writeText(b);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"8px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>Version {i+1}</div><div style={{fontSize:"11px",color:copied===i?C.success:"rgba(255,255,255,0.5)",fontWeight:"600"}}>{copied===i?"✓ Copied":"Copy"}</div></div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.85)",lineHeight:1.8}}>{b}</div><div style={{marginTop:"6px",fontSize:"10px",color:C.muted}}>{b.split(/\s+/).filter(Boolean).length} words</div></GlassCard>)}</div>}
  </ToolCard>);}

export function QuoraCommentGenerator(){
  const [answer,setAnswer]=useState("");const [style,setStyle]=useState("add insight");const [comments,setComments]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const styles=["Add Insight","Ask Question","Agree and Expand","Respectfully Disagree","Share Experience"];
  const generate=async()=>{if(!answer.trim())return;setLoading(true);setComments([]);const text=await askGemini(`Write 3 smart Quora comments on this answer: "${filterBad(answer.slice(0,500))}". Style: "${style}". Each comment should be 40 to 80 words, sound like a real thoughtful person, add genuine value or perspective, never be sycophantic ("great answer"), never use hyphens or em dashes. Make the commenter sound credible and knowledgeable. Return ONLY a valid JSON array of 3 strings. No markdown.`);const parsed=parseJSON(text);setComments(parsed&&Array.isArray(parsed)&&parsed.length?parsed:[]);setLoading(false);};
  return(<ToolCard title="Comment Generator" icon=""><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>PASTE THE ANSWER YOU WANT TO COMMENT ON</div><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Paste the Quora answer here..." style={{width:"100%",padding:"12px 16px",borderRadius:"12px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",height:"100px",resize:"none",marginBottom:"14px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>COMMENT STYLE</div><div style={{marginBottom:"16px"}}><NichePills niches={styles} active={style} onSelect={setStyle}/></div><GenButton onClick={generate} loading={loading} label="Generate Comments"/></GlassCard>
  {loading&&<Skeleton lines={3}/>}
  {!loading&&comments.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"8px"}}>{comments.map((c,i)=><GlassCard key={i} style={{cursor:"pointer"}} onClick={()=>{navigator.clipboard.writeText(c);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"8px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>Comment {i+1}</div><div style={{fontSize:"11px",color:copied===i?C.success:"rgba(255,255,255,0.5)",fontWeight:"600"}}>{copied===i?"✓ Copied":"Copy"}</div></div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.85)",lineHeight:1.8}}>{c}</div></GlassCard>)}</div>}
  </ToolCard>);}

export function QuoraDigestCreator(){
  const [answers,setAnswers]=useState("");const [topic,setTopic]=useState("");const [digest,setDigest]=useState(null);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(false);
  const generate=async()=>{if(!answers.trim()||!topic.trim())return;setLoading(true);setDigest(null);const text=await askGemini(`Convert these Quora answers about "${filterBad(topic)}" into a polished blog post / newsletter digest: "${filterBad(answers.slice(0,2000))}". Create: title (compelling, SEO friendly), intro paragraph (2-3 sentences hooking the reader), 3 to 5 key insights as sections (each with a heading and 2-3 paragraph elaboration), conclusion with takeaway. No hyphens or em dashes. Sound like a real expert writer. Return ONLY valid JSON: {"title":"...","intro":"...","sections":[{"heading":"...","content":"..."}],"conclusion":"..."}. No markdown.`);const parsed=parseJSON(text);setDigest(parsed&&parsed.title?parsed:null);setLoading(false);};
  const fullText=digest?`${digest.title}\n\n${digest.intro}\n\n${digest.sections?.map(s=>`${s.heading}\n\n${s.content}`).join("\n\n")}\n\n${digest.conclusion}`:"";
  return(<ToolCard title="Digest Creator" icon=""><GlassCard style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TOPIC / TITLE</div><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. How to grow on YouTube in 2026" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>PASTE YOUR QUORA ANSWERS</div><textarea value={answers} onChange={e=>setAnswers(e.target.value)} placeholder="Paste one or more Quora answers you wrote. The AI will turn them into a blog post or newsletter." style={{width:"100%",padding:"12px 16px",borderRadius:"12px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",height:"140px",resize:"none",marginBottom:"16px"}}/><GenButton onClick={generate} loading={loading} label="Create Digest"/></GlassCard>
  {loading&&<Skeleton lines={4}/>}
  {!loading&&digest&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}><div style={{display:"flex",justifyContent:"flex-end"}}><button onClick={()=>{navigator.clipboard.writeText(fullText);setCopied(true);setTimeout(()=>setCopied(false),2000);}} style={{padding:"8px 18px",borderRadius:"99px",border:"1px solid rgba(255,255,255,0.15)",background:"rgba(255,255,255,0.06)",color:copied?C.success:"rgba(255,255,255,0.7)",fontSize:"12px",fontWeight:"700",cursor:"pointer",fontFamily:"inherit"}}>{copied?"✓ Copied All":"Copy Full Post"}</button></div><GlassCard><div style={{fontSize:"20px",fontWeight:"900",color:"#fff",lineHeight:1.4,marginBottom:"12px"}}>{digest.title}</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.75)",lineHeight:1.8}}>{digest.intro}</div></GlassCard>{digest.sections?.map((s,i)=><GlassCard key={i}><div style={{fontSize:"15px",fontWeight:"800",color:"#fff",marginBottom:"8px"}}>{s.heading}</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.75)",lineHeight:1.8}}>{s.content}</div></GlassCard>)}<GlassCard style={{borderLeft:"3px solid rgba(255,255,255,0.3)"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",marginBottom:"6px"}}>Conclusion</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.75)",lineHeight:1.8}}>{digest.conclusion}</div></GlassCard></div>}
  </ToolCard>);}
