import { useState } from "react";
const C={green:"#25d366",glass:"rgba(255,255,255,0.04)",muted:"rgba(255,255,255,0.4)",success:"#34d399",danger:"#f87171"};
const AI="https://sociomeeai.com/api/ai/generate";
let lastCall=0;
const BAD_WORDS=['fuck','shit','bitch','nigger','faggot','chutiya','madarchod','bhenchod','randi','harami','gandu','motherfucker','child porn','cocaine','heroin','meth','jihad','massacre','genocide','bomb','suicide','terrorist','explosive','drug deal','illegal weapons','human trafficking','rape','molest','hack into','ransomware','darkweb','assassination'];
function filterBad(t){let s=t;BAD_WORDS.forEach(w=>{const re=new RegExp('\\b'+w+'\\b','gi');s=s.replace(re,'*'.repeat(w.length));});return s;}
async function askGemini(p){const now=Date.now();if(now-lastCall<3000)await new Promise(r=>setTimeout(r,3000-(now-lastCall)));lastCall=Date.now();try{const r=await fetch(AI,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[{role:"user",content:p}]})});if(!r.ok)return"";const d=await r.json();return d.content?.[0]?.text||"";}catch{return"";}}
function parseJSON(t){try{const c=t.replace(/```json|```/g,"").trim();const m=c.match(/(\[[\s\S]*\]|\{[\s\S]*\})/);return JSON.parse(m?m[1]:c);}catch{return null;}}
function renderWA(text){
  if(!text)return text;
  let t=text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
  t=t.replace(/\*([^*]+)\*/g,"<strong>$1</strong>");
  t=t.replace(/_([^_]+)_/g,"<em>$1</em>");
  return t;
}
function WAText({text}){
  return <div style={{fontSize:"13px",color:"rgba(255,255,255,0.85)",lineHeight:1.8,whiteSpace:"pre-line"}} dangerouslySetInnerHTML={{__html:renderWA(text||"")}}/>;
}
function TC({title,icon,children}){return <div style={{maxWidth:"700px",margin:"0 auto",padding:"20px 16px"}}><div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"20px"}}><span style={{fontSize:"20px"}}>{icon}</span><h2 style={{fontSize:"18px",fontWeight:"900",color:"#fff",margin:0}}>{title}</h2></div>{children}</div>;}
function GC({children,style={}}){return <div style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"16px",padding:"20px",...style}}>{children}</div>;}
function GB({onClick,loading,label="✦ Generate"}){return <button onClick={onClick} disabled={loading} style={{width:"100%",padding:"14px",borderRadius:"99px",border:"1.5px solid rgba(37,211,102,0.6)",background:loading?"rgba(37,211,102,0.05)":"rgba(37,211,102,0.15)",backdropFilter:"blur(16px)",color:"#fff",fontWeight:"800",fontSize:"14px",cursor:loading?"not-allowed":"pointer",fontFamily:"inherit",boxShadow:loading?"none":"0 0 24px rgba(37,211,102,0.4)",transition:"all 0.3s",opacity:loading?0.6:1}}>{loading?"Generating…":label}</button>;}
function NP({niches,active,onSelect}){return <div style={{display:"flex",gap:"6px",flexWrap:"wrap"}}>{niches.map(n=>{const a=active===n.toLowerCase();return <button key={n} onClick={()=>onSelect(n.toLowerCase())} style={{padding:"5px 12px",borderRadius:"99px",border:`1.5px solid ${a?"rgba(37,211,102,0.7)":"rgba(255,255,255,0.1)"}`,background:a?"rgba(37,211,102,0.15)":"transparent",color:a?"#4ade80":"rgba(255,255,255,0.5)",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{n}</button>;})}</div>;}
function SK({lines=3}){return <div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{Array(lines).fill(0).map((_,i)=><GC key={i}><div style={{display:"flex",flexDirection:"column",gap:"10px"}}><div style={{height:"12px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"40%"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"70%"}}/></div></GC>)}<style>{`@keyframes shimmer{to{background-position:-200% 0}}`}</style></div>;}

const BROADCAST_FB={business:["🎉 *Big Announcement!*\n\nHello {{name}}!\n\nWe have exciting news about {topic}.\n\n✅ What's new: [details here]\n✅ Available: Immediately\n✅ For you: Special offer inside\n\nReply YES to get all the details!\n\n_Team {brand}_\n\n_Reply STOP to unsubscribe_","📢 *{topic} Update*\n\nDear {{name}},\n\nThis is important. Please read carefully.\n\n{topic} is now available for you.\n\n👉 *What's new:* [details]\n👉 *Available from:* [date]\n👉 *Your benefit:* [specific benefit]\n\nTap below or reply to this message.\n\n_Regards, {brand}_\n\n_Reply STOP to unsubscribe_"],sale:["🔥 *SALE ALERT — Don't Miss This!*\n\nHi {{name}}! 👋\n\n*{topic}* is now at our BIGGEST discount.\n\n💰 Old Price: ₹[X]\n🎉 Your Price: ₹[Y]\n⏰ Only until: [date]\n\nUse code: *{brand}10* for extra 10% off!\n\n👇 Order now — limited stock!\n[link]\n\n_Reply STOP to unsubscribe_","⚡ *Flash Sale — {topic}!*\n\nHey {{name}},\n\nJust for the next 24 hours:\n\n🏷️ *30% OFF* on {topic}\n📦 Free delivery above ₹500\n🎁 Free gift with every order\n\nLast time we sold out in 3 hours!\n\nOrder: [link] or reply to this message\n\n_Team {brand}_\n\n_Reply STOP to unsubscribe_"],launch:["🚀 *It's Finally Here — {topic}!*\n\nHi {{name}}!\n\nAfter months of work, *{topic}* is LIVE.\n\n⭐ [Feature 1]\n⭐ [Feature 2]\n⭐ [Feature 3]\n\nEarly bird offer ends in 48 hours.\n\n👉 *Get it here:* [link]\n\nQuestions? Just reply! 😊\n\n_With love, {brand}_\n\n_Reply STOP to unsubscribe_"]};
const REPLY_FB={pricing:["Hi! 😊 Thanks for asking about our pricing.\n\n*Our Plans:*\n✅ Basic: ₹[X]/month\n✅ Pro: ₹[Y]/month\n✅ Enterprise: Custom pricing\n\nAll plans include [key benefit].\n\nWould you like a quick call to find the best fit? 📞","Great question! Pricing depends on your needs.\n\n📋 *Quick breakdown:*\n• Starter: ₹[X] — perfect for individuals\n• Business: ₹[Y] — for growing teams\n• Scale: ₹[Z] — unlimited everything\n\nFree demo available! Just let me know your preferred time 🙏"],complaint:["Hi, I'm really sorry to hear this 🙏\n\nYour experience matters deeply to us.\n\nCould you please share:\n1️⃣ Your order ID\n2️⃣ What exactly happened\n3️⃣ A photo if relevant\n\nWe'll resolve this within 24 hours, guaranteed. Thank you for your patience! 🙏","I sincerely apologize for the inconvenience 😔\n\nThis is not our standard.\n\n*What I'm doing right now:*\n→ Escalating to senior team\n→ Update within 2-4 hours\n→ Your issue is top priority\n\nHow can we make this right? 🙏"],inquiry:["Hi! 👋 Thanks for reaching out to *{brand}*!\n\nWe'd love to help. Here's what we offer:\n\n📦 {topic}\n✅ [Key benefit 1]\n✅ [Key benefit 2]\n✅ [Key benefit 3]\n\nInterested? I can set up a quick call or send more details. What works best for you?","Hello! Thank you for your interest in {brand} 😊\n\n{topic} is one of our most popular offerings!\n\n*Quick facts:*\n• Available: ✅\n• Delivery: [X] days\n• Price: Starting ₹[X]\n\nWould you like to place an order or need more info? 🙏"]};
const CHANNEL_FB={general:["📊 *{topic} — Weekly Update*\n\n{brand} | Weekly Digest\n\n*This week's highlights:*\n\n1️⃣ [Update 1 — be specific]\n2️⃣ [Update 2 — include a stat]\n3️⃣ [Update 3 — upcoming news]\n\n*Tip of the week:* [One actionable insight]\n\nForward this to someone who needs it! 🙏","🔔 *{topic} Alert — Important Update*\n\nHi everyone,\n\nQuick update that affects you:\n\n⚡ *What happened:* [brief summary]\n📅 *When:* [date]\n🎯 *Impact:* [direct impact on reader]\n\n*What to do:* [clear action]\n\nQuestions? Reply to this channel.\n\n_{brand}_"]};

export function WhatsAppBroadcast(){
  const [topic,setTopic]=useState("");const [brand,setBrand]=useState("");const [type,setType]=useState("business update");const [msgs,setMsgs]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const types=["Business Update","Sale/Offer","Product Launch","Event","Reminder","Community"];
  const getFB=(topic,brand,type)=>{const t=type.toLowerCase().split("/")[0].trim().replace(" update","").replace(" offer","");const pool=BROADCAST_FB[t]||BROADCAST_FB.business;return pool.map(m=>filterBad(m.replace(/{topic}/g,topic).replace(/{brand}/g,brand||"Our Team")));};
  const generate=async()=>{if(!topic.trim())return;setLoading(true);setMsgs([]);const text=await askGemini(`Write 2 WhatsApp broadcast messages for: topic="${filterBad(topic)}" brand="${filterBad(brand||"Brand")}" type="${type}". STRICT RULES: 1) Start with "Hey {{name}}!" — {{name}} is the personalization token, keep it exactly like that. 2) Use *bold* with asterisks for key words. 3) Under 200 words. 4) Warm personal Indian tone — like a friend texting not a corporation. 5) NO placeholders like [link] [date] [details] — write real example content. 6) NO "Reply STOP to unsubscribe" — this is WhatsApp not email. 7) End naturally like a real person would. 8) 3-5 emojis naturally placed. Return ONLY a valid JSON array of 2 strings. No markdown.`);const p=parseJSON(text);setMsgs((p&&Array.isArray(p)&&p.length)?p:getFB(topic,brand,type));setLoading(false);};
  return(<TC title="Broadcast Message Generator" icon="📢"><GC style={{marginBottom:"16px"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"14px"}}><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TOPIC / ANNOUNCEMENT *</div><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. new product launch, 50% sale, event invite" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>BRAND / SENDER NAME</div><input value={brand} onChange={e=>setBrand(e.target.value)} placeholder="e.g. SocioMee, Raj Textiles" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>MESSAGE TYPE</div><div style={{marginBottom:"16px"}}><NP niches={types} active={type} onSelect={setType}/></div><GB onClick={generate} loading={loading} label="✦ Generate Broadcast Messages"/></GC>
  {loading&&<SK lines={2}/>}
  {!loading&&msgs.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{msgs.map((m,i)=><GC key={i} style={{cursor:"pointer",borderLeft:"3px solid #25d366"}} onClick={()=>{navigator.clipboard.writeText(m);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:"10px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>Message {i+1}</div><div style={{fontSize:"11px",color:copied===i?C.success:"#4ade80",fontWeight:"600"}}>{copied===i?"✓ Copied":"Copy"}</div></div><WAText text={m}/><div style={{marginTop:"8px",fontSize:"10px",color:C.muted}}>{m.length} chars</div></GC>)}<GC style={{borderLeft:"3px solid #25d366"}}><div style={{fontSize:"10px",fontWeight:"700",color:"#4ade80",marginBottom:"6px"}}>💬 BROADCAST TIP</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.6)",lineHeight:1.6}}>Best time: 10 AM–12 PM or 7 PM–9 PM IST. Only message people who've saved your number. Personalize with {"{name}"} — increases open rates 40%. Never broadcast more than 3x per week.</div></GC></div>}
  </TC>);}

export function WhatsAppReplyTemplates(){
  const [scenario,setScenario]=useState("pricing inquiry");const [topic,setTopic]=useState("");const [brand,setBrand]=useState("");const [replies,setReplies]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const scenarios=["Pricing Inquiry","Complaint/Issue","Product Inquiry","Order Status","Appointment Booking","Thank You","Follow Up","Out of Office","Referral Ask","Payment Reminder"];
  const getFB=(scenario,topic,brand)=>{const s=scenario.toLowerCase().split("/")[0].trim().replace(" inquiry","").replace(" issue","");const pool=REPLY_FB[s]||REPLY_FB.inquiry;return pool.map(r=>filterBad(r.replace(/{brand}/g,brand||"Our Team").replace(/{topic}/g,topic||"our products")));};
  const generate=async()=>{setLoading(true);setReplies([]);const text=await askGemini(`Write 3 WhatsApp business reply templates for scenario: "${scenario}" business: "${filterBad(brand||"Business")}" product/service: "${filterBad(topic||"general")}". Rules: WhatsApp format *bold* _italic_. Professional but warm, not robotic. Under 200 words each. Clear next step. Indian context: use "Ji" "₹" where appropriate. 3 different tones: formal, friendly, follow-up. Return ONLY a valid JSON array of 3 strings. No markdown.`);const p=parseJSON(text);setReplies((p&&Array.isArray(p)&&p.length)?p:getFB(scenario,topic,brand));setLoading(false);};
  return(<TC title="Business Reply Templates" icon="💬"><GC style={{marginBottom:"16px"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"14px"}}><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>YOUR BUSINESS/BRAND</div><input value={brand} onChange={e=>setBrand(e.target.value)} placeholder="e.g. Priya Fashion, Tech Solutions" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>PRODUCT / SERVICE</div><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. sarees, web design, coaching" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>SCENARIO</div><div style={{marginBottom:"16px"}}><NP niches={scenarios} active={scenario} onSelect={setScenario}/></div><GB onClick={generate} loading={loading} label="✦ Generate Reply Templates"/></GC>
  {loading&&<SK lines={3}/>}
  {!loading&&replies.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{replies.map((r,i)=><GC key={i} style={{cursor:"pointer",borderLeft:"3px solid #25d366"}} onClick={()=>{navigator.clipboard.writeText(r);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:"10px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>Template {i+1}</div><div style={{fontSize:"11px",color:copied===i?C.success:"#4ade80",fontWeight:"600"}}>{copied===i?"✓ Copied":"Copy"}</div></div><WAText text={r}/></GC>)}</div>}
  </TC>);}

export function WhatsAppChannelPost(){
  const [topic,setTopic]=useState("");const [brand,setBrand]=useState("");const [type,setType]=useState("business update");const [posts,setPosts]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const types=["Business Update","Motivation/Tip","News/Alert","Product Showcase","Weekly Digest","Educational","Offer/Deal"];
  const getFB=(topic,brand)=>{const pool=CHANNEL_FB.general;return pool.map(p=>filterBad(p.replace(/{topic}/g,topic).replace(/{brand}/g,brand||"Our Channel")));};
  const generate=async()=>{if(!topic.trim())return;setLoading(true);setPosts([]);const text=await askGemini(`Write 2 WhatsApp Channel posts for: topic="${filterBad(topic)}" channel="${filterBad(brand||"Channel")}" type="${type}". Rules: *bold* _italic_ WhatsApp format. 100-250 words. Editorial/newsletter feel. Emoji lists for scanability. Forward-worthy insight. Indian context where relevant. End with 👍 for yes or ❤️ to agree. Return ONLY a valid JSON array of 2 strings. No markdown.`);const p=parseJSON(text);setPosts((p&&Array.isArray(p)&&p.length)?p:getFB(topic,brand));setLoading(false);};
  return(<TC title="Channel Post Generator" icon="📺"><GC style={{marginBottom:"16px"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"14px"}}><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TOPIC *</div><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. market update, fitness tip, product news" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>CHANNEL NAME</div><input value={brand} onChange={e=>setBrand(e.target.value)} placeholder="e.g. SocioMee Updates, Daily Finance" style={{width:"100%",padding:"10px 14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>POST TYPE</div><div style={{marginBottom:"16px"}}><NP niches={types} active={type} onSelect={setType}/></div><GB onClick={generate} loading={loading} label="✦ Generate Channel Posts"/></GC>
  {loading&&<SK lines={2}/>}
  {!loading&&posts.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{posts.map((p,i)=><GC key={i} style={{cursor:"pointer",borderLeft:"3px solid #25d366"}} onClick={()=>{navigator.clipboard.writeText(p);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:"10px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>Post {i+1}</div><div style={{fontSize:"11px",color:copied===i?C.success:"#4ade80",fontWeight:"600"}}>{copied===i?"✓ Copied":"Copy"}</div></div><WAText text={p}/></GC>)}</div>}
  </TC>);}
