import { useState } from "react";
const C={glass:"rgba(255,255,255,0.04)",muted:"rgba(255,255,255,0.4)",success:"#34d399",danger:"#f87171"};
const AI="https://sociomee.in/api/ai/generate";
let lastCall=0;
const BAD_WORDS=['fuck','shit','bitch','nigger','faggot','chutiya','madarchod','bhenchod','randi','harami','gandu','motherfucker','child porn','cocaine','heroin','meth','jihad','massacre','genocide','bomb','suicide','terrorist','explosive','drug deal','illegal weapons','human trafficking','rape','molest','hack into','ransomware','darkweb','assassination'];
function filterBad(t){let s=t;BAD_WORDS.forEach(w=>{const re=new RegExp('\\b'+w+'\\b','gi');s=s.replace(re,'*'.repeat(w.length));});return s;}
async function askGemini(p){const now=Date.now();if(now-lastCall<3000)await new Promise(r=>setTimeout(r,3000-(now-lastCall)));lastCall=Date.now();try{const r=await fetch(AI,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[{role:"user",content:p}]})});if(!r.ok)return"";const d=await r.json();return d.content?.[0]?.text||"";}catch{return"";}}
function parseJSON(t){try{const c=t.replace(/```json|```/g,"").trim();const m=c.match(/(\[[\s\S]*\]|\{[\s\S]*\})/);return JSON.parse(m?m[1]:c);}catch{return null;}}
function TC({title,icon,children}){return <div style={{maxWidth:"700px",margin:"0 auto",padding:"20px 16px"}}><div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"20px"}}><span style={{fontSize:"20px"}}>{icon}</span><h2 style={{fontSize:"18px",fontWeight:"900",color:"#fff",margin:0}}>{title}</h2></div>{children}</div>;}
function GC({children,style={}}){return <div style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"16px",padding:"20px",...style}}>{children}</div>;}
function GB({onClick,loading,label="✦ Generate"}){return <button onClick={onClick} disabled={loading} style={{width:"100%",padding:"14px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.4)",background:loading?"rgba(255,255,255,0.03)":"rgba(255,255,255,0.08)",backdropFilter:"blur(16px)",color:"#fff",fontWeight:"800",fontSize:"14px",cursor:loading?"not-allowed":"pointer",fontFamily:"inherit",boxShadow:loading?"none":"0 0 24px rgba(255,255,255,0.15)",transition:"all 0.3s",opacity:loading?0.6:1}}>{loading?"Generating…":label}</button>;}
function NP({niches,active,onSelect}){return <div style={{display:"flex",gap:"6px",flexWrap:"wrap"}}>{niches.map(n=>{const a=active===n.toLowerCase();return <button key={n} onClick={()=>onSelect(n.toLowerCase())} style={{padding:"5px 12px",borderRadius:"99px",border:`1.5px solid ${a?"rgba(255,255,255,0.6)":"rgba(255,255,255,0.1)"}`,background:a?"rgba(255,255,255,0.12)":"transparent",color:a?"#fff":"rgba(255,255,255,0.5)",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{n}</button>;})}</div>;}
function SK({lines=3}){return <div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{Array(lines).fill(0).map((_,i)=><GC key={i}><div style={{display:"flex",flexDirection:"column",gap:"10px"}}><div style={{height:"12px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"40%"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"70%"}}/></div></GC>)}<style>{`@keyframes shimmer{to{background-position:-200% 0}}`}</style></div>;}

const TWEET_FB={tech:["Hot take: {topic} is the most important shift in tech this decade and 90% of people are still treating it like a toy.\n\nThe ones building with it right now will be untouchable in 5 years.\n\nChange my mind.","Everyone is talking about {topic}.\nNobody is actually using it to build.\n\nStop consuming. Start creating.\n\nThe gap between those two groups is where the opportunity lives."],startup:["Every startup that failed at {topic} made the same mistake:\n\nThey optimized for looking good instead of being good.\n\nInstagram strategy > actual strategy.\nLinkedIn posts > actual execution.\n\nShip something. Anything.","Founders who've figured out {topic}:\n→ Talk about customers obsessively\n→ Know their unit economics cold\n→ Read more than they post\n\nEverything else is noise."],finance:["The {topic} truth that nobody on financial Twitter will tell you:\n\nMost 'advice' is survivorship bias.\nMost 'strategies' are for people who already have money.\n\nHere's what actually works at the start 👇","Rich people don't talk about {topic} the way the internet does.\n\nThey talk about:\n→ Time horizons\n→ Asymmetric bets\n→ Compound effects\n\nNot tips. Not shortcuts."],india:["The way India is approaching {topic} is fundamentally different from the West.\n\nAnd I think we're going to win.\n\nHere's why 🇮🇳","Nobody in Indian tech Twitter talks about {topic} honestly.\n\nEveryone's building in public but nobody's failing in public.\n\nHere's my honest take:"],general:["The {topic} thing I wish someone told me 3 years ago:\n\nIt's not about being the best.\nIt's about showing up consistently when others don't.\n\nThat's it. That's the whole secret.","Unpopular opinion: {topic} is simple.\n\nWhat's complicated is the discipline to do the simple things consistently.\n\nMost people want complexity as an excuse not to start."]};
const HOOK_FB={general:["Hot take: {topic} is broken and nobody wants to admit it","The {topic} conversation nobody in this space is willing to have","I've been wrong about {topic} for years. Here's what changed my mind","Unpopular opinion about {topic} that will get me ratio'd but I stand by it","99% of people struggle with {topic} because of this one thing (it's not what you think)"],tech:["AI won't replace {topic}. But {topic} done with AI will replace {topic} done without it","Hot take: everything you've been told about {topic} is cope","The {topic} skill that matters in 2024 isn't what anyone's teaching","I've tested every {topic} tool. Here's the honest tier list no one will publish"],finance:["Your {topic} strategy is designed to make you poor (a thread)","The honest math on {topic} that financial influencers won't show you","Why I stopped listening to {topic} advice from anyone with under $10M"],india:["India's approach to {topic} is about to leapfrog the West and nobody's talking about it 🇮🇳","The desi take on {topic} that global 'experts' completely miss","Building {topic} for Bharat is a different game. Here's what I've learned"]};
const TIME_FB={india:{times:[{time:"7:00 AM – 9:00 AM IST",reason:"Morning X session — professionals check before work, highest impressions",score:94,day:"Weekdays"},{time:"12:00 PM – 2:00 PM IST",reason:"Lunch scroll — decision makers active, high engagement rate",score:87,day:"Weekdays"},{time:"8:00 PM – 10:00 PM IST",reason:"Evening prime time — highest engagement on X India",score:96,day:"All days"},{time:"9:00 PM – 11:00 PM IST",reason:"Late evening — tech/finance/startup crowd most active",score:91,day:"All days"}],best_days:["Tuesday","Wednesday","Thursday","Friday"],avoid:["Saturday afternoon","Sunday morning","Monday morning"],tip:"X 2024 algorithm: Replies boost reach 5x more than retweets. Quote tweets with your take > plain retweets. No external links in first post — kills reach. Reply to big accounts in your niche within first hour of their post. Strong opinion > generic insight every time.",frequency:"3-5 posts per day. 1-2 threads per week for maximum growth."}};

export function XTweetGenerator(){
  const [topic,setTopic]=useState("");const [niche,setNiche]=useState("general");const [tone,setTone]=useState("controversial take");const [tweets,setTweets]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["General","Tech","Finance","Startup","Marketing","AI","India","Crypto","Politics","Science","Sports","Bollywood","Fitness","Philosophy","Business","Creator Economy","Web3","Climate","Media","Education","Edtech","Fintech","D2C","SaaS","Angel Investing","VC","Public Policy","Journalism","Law","Healthcare","Mental Health","Sustainability","Space","Gaming","Anime","Books","History","Economics","Psychology","Geopolitics","Cybersecurity","Data Science","Product Management","Design","Architecture"];
  const tones=["Controversial Take","Hot Take","Thread Opener","Observation","Prediction","Story","Rant","Insight"];
  const getFB=(topic,niche)=>{const pool=TWEET_FB[niche]||TWEET_FB.general;return[...pool].sort(()=>Math.random()-0.5).slice(0,3).map(t=>filterBad(t.replace(/{topic}/g,topic)));};
  const generate=async()=>{if(!topic.trim())return;setLoading(true);setTweets([]);const text=await askGemini(`Write 3 viral X (Twitter) posts about: "${filterBad(topic)}" niche: ${niche} tone: ${tone}. X ALGORITHM RULES: No external links (kills reach). 200-260 chars sweet spot. Short punchy lines not paragraphs. Hooks: "Hot take:" "Unpopular opinion:" "I've been wrong about..." "Nobody talks about...". Indian context where relevant. Controversial/strong opinion = 3x more engagement. Tone ${tone}: ${tone==="controversial take"?"Bold claim, will divide, confident":tone==="hot take"?"Fast edgy opinion, high conviction":tone==="thread opener"?"Ends with 🧵, creates massive curiosity":"Direct, punchy, memorable"}. Return ONLY a valid JSON array of 3 strings. No markdown.`);const p=parseJSON(text);setTweets((p&&Array.isArray(p)&&p.length)?p:getFB(topic,niche));setLoading(false);};
  return(<TC title="Post Generator" icon="𝕏"><GC style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TOPIC</div><input value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>e.key==="Enter"&&generate()} placeholder="e.g. AI replacing jobs, Indian startup ecosystem, crypto winter" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><div style={{marginBottom:"14px"}}><NP niches={niches} active={niche} onSelect={setNiche}/></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TONE</div><div style={{marginBottom:"16px"}}><NP niches={tones} active={tone} onSelect={setTone}/></div><GB onClick={generate} loading={loading} label="✦ Generate Posts"/></GC>
  {loading&&<SK lines={3}/>}
  {!loading&&tweets.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{tweets.map((t,i)=><GC key={i} style={{cursor:"pointer",borderLeft:`3px solid ${i===0?"#fff":"rgba(255,255,255,0.2)"}`}} onClick={()=>{navigator.clipboard.writeText(t);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:"10px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>Post {i+1}</div><div style={{fontSize:"11px",color:copied===i?C.success:"rgba(255,255,255,0.5)",fontWeight:"600"}}>{copied===i?"✓ Copied":"Copy"}</div></div><div style={{fontSize:"14px",color:"rgba(255,255,255,0.9)",lineHeight:1.7,whiteSpace:"pre-line"}}>{t}</div><div style={{marginTop:"8px",fontSize:"10px",color:t.length>280?C.danger:C.muted}}>{t.length}/280 chars {t.length>280?"⚠️ Over limit":"✓"}</div></GC>)}<GC style={{borderLeft:"3px solid rgba(255,255,255,0.3)"}}><div style={{fontSize:"10px",fontWeight:"700",color:"rgba(255,255,255,0.5)",marginBottom:"6px"}}>𝕏 ALGORITHM TIP</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.6)",lineHeight:1.6}}>No links in post — put in first reply. Replies = 5x more reach than RTs. Reply to big accounts in your niche within first hour. Post 7-9 AM or 8-10 PM IST. Strong opinion > generic insight every time.</div></GC></div>}
  </TC>);}

export function XThreadGenerator(){
  const [topic,setTopic]=useState("");const [niche,setNiche]=useState("general");const [tone,setTone]=useState("educational");const [thread,setThread]=useState(null);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["General","Tech","Finance","Startup","Marketing","AI","India","Crypto","Business","Creator Economy","Education","Fitness","Philosophy","Science","Media"];
  const tones=["Educational","Controversial","Personal Story","Data & Insights","Prediction","How-to","Opinion","Listicle"];
  const getFB=(topic)=>({hook:`The ${topic} thread nobody asked for but everyone needs:\n\n🧵`,intro:`1/ Most people approach ${topic} completely wrong.\n\nThey start with tactics instead of principles.\n\nHere's the framework that actually works:`,parts:[`2/ First: understand WHY ${topic} matters.\n\nNot the surface reason. The deep reason.\n\nMost people never get past the surface.`,`3/ Second: identify the ONE thing in ${topic} that drives 80% of results.\n\nIt's almost never what you think.\n\nUsually something boring and unsexy.`,`4/ Third: do that one thing consistently for 90 days before adding anything else.\n\nResistance to this advice is how you know it's right.`,`5/ The result?\n\nTop 5% of ${topic} practitioners without trying.\n\nThe bar is low because consistency is rare.`],cta:`6/ RT if this was useful 🙏\n\nFollow for more ${topic} threads.\n\nWhat would you add?`});
  const generate=async()=>{if(!topic.trim())return;setLoading(true);setThread(null);const text=await askGemini(`Write a viral X thread about: "${filterBad(topic)}" niche: ${niche} tone: ${tone}. Tweet 1 Hook: max 240 chars, massive curiosity, ends with 🧵, NO links. Tweet 2 Intro: 200-250 chars, build anticipation. Tweets 3-7 Body: each 150-220 chars, one insight per tweet. Tweet 8 CTA: ask for RT or reply. Indian context where relevant. No links in any tweet. Return ONLY valid JSON: {"hook":"tweet 1","intro":"tweet 2","parts":["tweet 3","tweet 4","tweet 5","tweet 6","tweet 7"],"cta":"tweet 8"}. No markdown.`);const p=parseJSON(text);setThread((p&&p.hook)?p:getFB(topic));setLoading(false);};
  const allTweets=thread?[{label:"1/ Hook 🎣",text:thread.hook,accent:"#fff"},{label:"2/ Intro",text:thread.intro,accent:"rgba(255,255,255,0.5)"},...(thread.parts||[]).map((t,i)=>({label:`${i+3}/ Body`,text:t,accent:"rgba(255,255,255,0.3)"})),{label:`${(thread.parts?.length||5)+3}/ CTA`,text:thread.cta,accent:"#34d399"}]:[];
  const copyAll=()=>{if(!thread)return;navigator.clipboard.writeText([thread.hook,thread.intro,...(thread.parts||[]),thread.cta].join("\n\n---\n\n"));setCopied("all");setTimeout(()=>setCopied(null),2000);};
  return(<TC title="Thread Generator" icon="🧵"><GC style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TOPIC</div><input value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>e.key==="Enter"&&generate()} placeholder="e.g. how I grew to 10K followers, AI tools for founders" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><div style={{marginBottom:"14px"}}><NP niches={niches} active={niche} onSelect={setNiche}/></div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TONE</div><div style={{marginBottom:"16px"}}><NP niches={tones} active={tone} onSelect={setTone}/></div><GB onClick={generate} loading={loading} label="✦ Generate Thread"/></GC>
  {loading&&<SK lines={5}/>}
  {!loading&&thread&&<><div style={{display:"flex",justifyContent:"flex-end",marginBottom:"10px"}}><button onClick={copyAll} style={{padding:"7px 18px",borderRadius:"99px",border:"1px solid rgba(255,255,255,0.2)",background:"rgba(255,255,255,0.06)",color:copied==="all"?C.success:"rgba(255,255,255,0.7)",fontSize:"12px",fontWeight:"700",cursor:"pointer",fontFamily:"inherit"}}>{copied==="all"?"✓ Copied All":"Copy Full Thread"}</button></div><div style={{display:"flex",flexDirection:"column",gap:"8px"}}>{allTweets.map((tw,i)=><GC key={i} style={{borderLeft:`3px solid ${tw.accent}`,cursor:"pointer"}} onClick={()=>{navigator.clipboard.writeText(tw.text);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"8px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase"}}>{tw.label}</div><div style={{fontSize:"11px",color:copied===i?C.success:"rgba(255,255,255,0.4)",fontWeight:"600"}}>{copied===i?"✓":"Copy"}</div></div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.85)",lineHeight:1.6,whiteSpace:"pre-line"}}>{tw.text}</div><div style={{marginTop:"6px",fontSize:"10px",color:tw.text?.length>280?C.danger:C.muted}}>{tw.text?.length}/280</div></GC>)}</div></>}
  </TC>);}

export function XHookGenerator(){
  const [topic,setTopic]=useState("");const [niche,setNiche]=useState("general");const [hooks,setHooks]=useState([]);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["General","Tech","Finance","Startup","Marketing","AI","India","Crypto","Business","Creator Economy","Education","Fitness","Philosophy","Science","Media","Sports","Bollywood","Web3","Climate","Politics"];
  const getFB=(topic,niche)=>{const pool=HOOK_FB[niche]||HOOK_FB.general;return[...pool].sort(()=>Math.random()-0.5).slice(0,5).map(h=>filterBad(h.replace(/{topic}/g,topic)));};
  const generate=async()=>{if(!topic.trim())return;setLoading(true);setHooks([]);const text=await askGemini(`Write 5 viral X hooks for: "${filterBad(topic)}" niche: ${niche}. Max 240 chars each. Mix formats: "Hot take:" "Unpopular opinion:" "I've been wrong about..." "The X truth about Y:" "Nobody talks about..." bold prediction, contrarian take. Create strong emotion: curiosity, disagreement, FOMO. Should make people want to argue OR share. Indian context where relevant. Statements perform 3x better than questions. Return ONLY a valid JSON array of 5 strings. No markdown.`);const p=parseJSON(text);setHooks((p&&Array.isArray(p)&&p.length)?p:getFB(topic,niche));setLoading(false);};
  return(<TC title="Hook Generator" icon="🪝"><GC style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TOPIC</div><input value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>e.key==="Enter"&&generate()} placeholder="e.g. building in public, AI tools, Indian startup funding" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><div style={{marginBottom:"16px"}}><NP niches={niches} active={niche} onSelect={setNiche}/></div><GB onClick={generate} loading={loading} label="✦ Generate Hooks"/></GC>
  {loading&&<SK lines={5}/>}
  {!loading&&hooks.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"10px"}}>{hooks.map((h,i)=><GC key={i} style={{display:"flex",alignItems:"flex-start",gap:"12px",cursor:"pointer",borderLeft:i===0?"3px solid #fff":"3px solid transparent"}} onClick={()=>{navigator.clipboard.writeText(h);setCopied(i);setTimeout(()=>setCopied(null),2000);}}><div style={{width:"24px",height:"24px",borderRadius:"50%",background:"rgba(255,255,255,0.1)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"11px",fontWeight:"800",color:"rgba(255,255,255,0.6)",flexShrink:0}}>{i+1}</div><div style={{flex:1,fontSize:"14px",color:"rgba(255,255,255,0.85)",lineHeight:1.6}}>{h}</div><div style={{fontSize:"11px",color:copied===i?C.success:"rgba(255,255,255,0.4)",fontWeight:"600",flexShrink:0}}>{copied===i?"✓":"Copy"}</div></GC>)}<GC style={{borderLeft:"3px solid rgba(255,255,255,0.2)"}}><div style={{fontSize:"10px",fontWeight:"700",color:"rgba(255,255,255,0.4)",marginBottom:"6px"}}>𝕏 HOOK TIP</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.6)",lineHeight:1.6}}>Statement hooks outperform questions 3:1. "Hot take" and "Unpopular opinion" trigger engagement prediction. First 60 mins after posting is everything — reply to every comment immediately.</div></GC></div>}
  </TC>);}

export function XBestTime(){
  const [niche,setNiche]=useState("general");const [audience,setAudience]=useState("india");const [result,setResult]=useState(null);const [loading,setLoading]=useState(false);
  const niches=["general","tech","finance","startup","marketing","ai","india","crypto","business","creator economy","education","fitness","philosophy","science","media","sports","bollywood","web3","politics"];
  const audiences=[{id:"india",label:"India (IST)"},{id:"global",label:"Global (EST)"},{id:"usa",label:"USA"},{id:"uk",label:"UK & Europe"},{id:"australia",label:"Australia"},{id:"middle_east",label:"Middle East"}];
  const analyze=async()=>{setLoading(true);setResult(null);const text=await askGemini(`Best times to post on X (Twitter) for niche: "${niche}" audience: "${audience}". Return ONLY valid JSON: {"times":[{"time":"7:00 AM – 9:00 AM IST","reason":"reason","score":94,"day":"Weekdays"}],"best_days":["Tuesday"],"avoid":["Saturday afternoon"],"tip":"specific X 2024 algorithm tip","frequency":"X posts per day"} 3-4 slots. Score out of 100.`);const p=parseJSON(text);setResult((p&&p.times)?p:(TIME_FB[audience]||TIME_FB.india));setLoading(false);};
  const sc=s=>s>=90?"#34d399":s>=80?"#f59e0b":"#f87171";
  return(<TC title="Best Time to Post" icon="⏰"><GC style={{marginBottom:"16px"}}><div style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><NP niches={niches} active={niche} onSelect={setNiche}/></div><div style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>AUDIENCE</div><div style={{display:"flex",flexWrap:"wrap",gap:"6px"}}>{audiences.map(a=><button key={a.id} onClick={()=>setAudience(a.id)} style={{padding:"5px 14px",borderRadius:"99px",border:`1.5px solid ${audience===a.id?"rgba(255,255,255,0.6)":"rgba(255,255,255,0.1)"}`,background:audience===a.id?"rgba(255,255,255,0.12)":"transparent",color:audience===a.id?"#fff":"rgba(255,255,255,0.5)",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{a.label}</button>)}</div></div><GB onClick={analyze} loading={loading} label="✦ Analyze Best Times"/></GC>
  {loading&&<SK lines={3}/>}
  {!loading&&result&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}><GC><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"12px"}}>🕐 Best Times</div>{result.times?.map((t,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:"12px",padding:"10px 14px",borderRadius:"12px",background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.06)",marginBottom:"8px"}}><div style={{fontSize:"20px",fontWeight:"900",color:sc(t.score),minWidth:"36px",textAlign:"center"}}>{t.score}</div><div style={{flex:1}}><div style={{fontSize:"13px",fontWeight:"700",color:"#fff",marginBottom:"2px"}}>{t.time} <span style={{fontSize:"10px",color:C.muted}}>· {t.day}</span></div><div style={{fontSize:"11px",color:C.muted}}>{t.reason}</div></div><div style={{width:"5px",height:"36px",borderRadius:"99px",background:sc(t.score),opacity:0.7}}/></div>)}</GC><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px"}}><GC><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"10px"}}>✅ Best Days</div>{result.best_days?.map((d,i)=><div key={i} style={{fontSize:"13px",color:"#34d399",fontWeight:"600",marginBottom:"4px"}}>• {d}</div>)}</GC><GC><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"10px"}}>❌ Avoid</div>{result.avoid?.map((d,i)=><div key={i} style={{fontSize:"11px",color:"#f87171",fontWeight:"600",marginBottom:"4px"}}>• {d}</div>)}</GC></div><GC style={{borderLeft:"3px solid rgba(255,255,255,0.4)"}}><div style={{fontSize:"10px",fontWeight:"700",color:"rgba(255,255,255,0.5)",marginBottom:"6px"}}>𝕏 ALGORITHM TIP</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.8)",lineHeight:1.6,marginBottom:"8px"}}>{result.tip}</div><div style={{fontSize:"12px",color:C.muted}}>📅 <span style={{color:"rgba(255,255,255,0.7)",fontWeight:"700"}}>{result.frequency}</span></div></GC></div>}
  </TC>);}
