import { useState } from "react";
const C={purple:"#7c3aed",glass:"rgba(255,255,255,0.04)",muted:"rgba(255,255,255,0.4)",success:"#a78bfa",danger:"#a78bfa",yellow:"#7c3aed"};
const BASE="https://sociomee.in/api";
async function apiFetch(path,body){const r=await fetch(`${BASE}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});return r.json();}
function GC({children,style={}}){return <div style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"16px",padding:"20px",...style}}>{children}</div>;}
function GB({onClick,loading,label="✦ Generate",color="#7c3aed"}){return <button onClick={onClick} disabled={loading} style={{width:"100%",padding:"14px",borderRadius:"99px",border:`1.5px solid ${color}99`,background:loading?`${color}0d`:`${color}26`,backdropFilter:"blur(16px)",color:"#fff",fontWeight:"800",fontSize:"14px",cursor:loading?"not-allowed":"pointer",fontFamily:"inherit",boxShadow:loading?"none":`0 0 24px ${color}66`,transition:"all 0.3s",opacity:loading?0.6:1}}>{loading?"Loading…":label}</button>;}
function NP({niches,active,onSelect,color="#7c3aed"}){return <div style={{display:"flex",gap:"6px",flexWrap:"wrap"}}>{niches.map(n=>{const a=active===n.toLowerCase();return <button key={n} onClick={()=>onSelect(n.toLowerCase())} style={{padding:"5px 12px",borderRadius:"99px",border:`1.5px solid ${a?color+"aa":"rgba(255,255,255,0.1)"}`,background:a?color+"26":"transparent",color:a?"#fff":"rgba(255,255,255,0.5)",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{n}</button>;})}</div>;}
function SK(){return <div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{[1,2,3].map(i=><GC key={i}><div style={{display:"flex",flexDirection:"column",gap:"10px"}}><div style={{height:"12px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite",width:"40%"}}/><div style={{height:"14px",borderRadius:"6px",background:"linear-gradient(90deg,rgba(255,255,255,0.04) 25%,rgba(255,255,255,0.08) 50%,rgba(255,255,255,0.04) 75%)",backgroundSize:"200% 100%",animation:"shimmer 1.5s infinite"}}/></div></GC>)}<style>{`@keyframes shimmer{to{background-position:-200% 0}}`}</style></div>;}
function TC({title,icon,children}){return <div style={{maxWidth:"800px",margin:"0 auto",padding:"20px 16px"}}><div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"20px"}}><span style={{fontSize:"20px"}}>{icon}</span><h2 style={{fontSize:"18px",fontWeight:"900",color:"#fff",margin:0}}>{title}</h2></div>{children}</div>;}
function fmtNum(n){if(!n)return"0";if(n>=1000000)return(n/1000000).toFixed(1)+"M";if(n>=1000)return(n/1000).toFixed(1)+"K";return n.toString();}

export function KeywordResearch(){
  const [kw,setKw]=useState("");const [country,setCountry]=useState("IN");const [data,setData]=useState(null);const [loading,setLoading]=useState(false);
  const search=async()=>{if(!kw.trim())return;setLoading(true);setData(null);const r=await apiFetch("/youtube-tools/keyword-research",{keyword:kw,country});setData(r);setLoading(false);};
  const scoreColor=s=>s>=75?C.success:s>=50?C.yellow:C.danger;
  const compColor=c=>c==="Low"?C.success:c==="Medium"?C.yellow:C.danger;
  return(<TC title="Keyword Research" icon="🔍"><GC style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>KEYWORD / TOPIC</div><div style={{display:"flex",gap:"10px",marginBottom:"14px"}}><input value={kw} onChange={e=>setKw(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="e.g. how to edit videos, indian cooking, stock market" style={{flex:1,padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none"}}/><div style={{display:"flex",gap:"6px",flexWrap:"wrap"}}>{[{id:"IN",label:"India"},{id:"US",label:"USA"},{id:"GB",label:"UK"},{id:"CA",label:"Canada"},{id:"AU",label:"Australia"}].map(ct=><button key={ct.id} onClick={()=>setCountry(ct.id)} style={{padding:"5px 12px",borderRadius:"99px",border:`1.5px solid ${country===ct.id?"rgba(124,58,237,0.7)":"rgba(255,255,255,0.1)"}`,background:country===ct.id?"rgba(124,58,237,0.15)":"transparent",color:country===ct.id?"#a78bfa":"rgba(255,255,255,0.5)",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{ct.label}</button>)}</div></div><GB onClick={search} loading={loading} label="✦ Research Keyword"/></GC>
  {loading&&<SK/>}
  {!loading&&data&&!data.error&&<div style={{display:"flex",flexDirection:"column",gap:"14px"}}>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px"}}>
      <GC style={{textAlign:"center"}}><div style={{fontSize:"36px",fontWeight:"900",color:scoreColor(data.opportunity_score)}}>{data.opportunity_score}</div><div style={{fontSize:"11px",color:C.muted,textTransform:"uppercase",letterSpacing:"1px"}}>Opportunity Score</div></GC>
      <GC><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>💡 PRO TIP</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.7)",lineHeight:1.6}}>{data.tip}</div></GC>
    </div>
    {data.related_keywords?.length>0&&<GC><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"12px"}}>🎯 Related Keywords</div><div style={{display:"flex",flexDirection:"column",gap:"8px"}}>{data.related_keywords.map((k,i)=><div key={i} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"8px 12px",borderRadius:"10px",background:"rgba(255,255,255,0.03)"}}><span style={{fontSize:"13px",color:"#fff",fontWeight:"600"}}>{k.keyword}</span><div style={{display:"flex",alignItems:"center",gap:"8px"}}><span style={{fontSize:"10px",fontWeight:"700",color:compColor(k.competition),padding:"2px 8px",borderRadius:"99px",background:compColor(k.competition)+"18"}}>{k.competition}</span><span style={{fontSize:"11px",color:scoreColor(k.opportunity||50),fontWeight:"700"}}>{k.opportunity||50}%</span></div></div>)}</div></GC>}
    {data.longtail?.length>0&&<GC><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"10px"}}>🐢 Long-tail Keywords</div><div style={{display:"flex",flexWrap:"wrap",gap:"6px"}}>{data.longtail.map((t,i)=><span key={i} style={{padding:"5px 12px",borderRadius:"99px",background:"rgba(124,58,237,0.12)",border:"1px solid rgba(124,58,237,0.25)",color:"#a78bfa",fontSize:"12px",fontWeight:"600",cursor:"pointer"}} onClick={()=>navigator.clipboard.writeText(t)}>{t}</span>)}</div></GC>}
    {data.top_videos?.length>0&&<GC><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"12px"}}>📹 Top Videos for This Keyword</div><div style={{display:"flex",flexDirection:"column",gap:"8px"}}>{data.top_videos.slice(0,5).map((v,i)=><div key={i} style={{display:"flex",gap:"12px",alignItems:"center",padding:"8px",borderRadius:"10px",background:"rgba(255,255,255,0.03)"}}><img src={v.thumbnail} alt="" style={{width:"80px",height:"45px",borderRadius:"6px",objectFit:"cover",flexShrink:0}}/><div style={{flex:1,minWidth:0}}><div style={{fontSize:"12px",color:"#fff",fontWeight:"600",lineHeight:1.4,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{v.title}</div><div style={{fontSize:"10px",color:C.muted,marginTop:"2px"}}>{v.channel} · {v.published}</div></div><a href={`https://youtube.com/watch?v=${v.video_id}`} target="_blank" rel="noreferrer" style={{fontSize:"10px",color:"#a78bfa",textDecoration:"none",flexShrink:0}}>▶ Watch</a></div>)}</div></GC>}
  </div>}
  </TC>);}

export function TrendingVideos(){
  const [niche,setNiche]=useState("general");const [country,setCountry]=useState("IN");const [data,setData]=useState(null);const [loading,setLoading]=useState(false);
  const niches=["General","Gaming","Music","Tech","Education","Entertainment","News","Sports","Comedy","Food","Fitness","Travel","Fashion","Finance","Bollywood","Cricket","DIY","Beauty","Science","Motivation","Kids","Cooking","Vlog","Cars"];
  const [vtype,setVtype]=useState("all");const fetch_=async()=>{setLoading(true);setData(null);const r=await apiFetch("/youtube-tools/trending",{niche,country,video_type:vtype});setData(r);setLoading(false);};
  return(<TC title="Trending Videos" icon="🔥"><GC style={{marginBottom:"16px"}}><div style={{marginBottom:"14px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><NP niches={niches} active={niche} onSelect={setNiche} color="#7c3aed"/></div><div style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>REGION</div><div style={{display:"flex",gap:"6px",flexWrap:"wrap"}}>{[{id:"IN",flag:"🇮🇳",label:"India"},{id:"US",flag:"🇺🇸",label:"USA"},{id:"GB",flag:"🇬🇧",label:"UK"},{id:"JP",flag:"🇯🇵",label:"Japan"},{id:"BR",flag:"🇧🇷",label:"Brazil"}].map(c=><button key={c.id} onClick={()=>setCountry(c.id)} style={{padding:"5px 14px",borderRadius:"99px",border:`1.5px solid ${country===c.id?"rgba(124,58,237,0.7)":"rgba(255,255,255,0.1)"}`,background:country===c.id?"rgba(124,58,237,0.15)":"transparent",color:"#fff",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{c.flag} {c.label}</button>)}</div></div><div style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:"rgba(255,255,255,0.4)",textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>TYPE</div><div style={{display:"flex",gap:"6px"}}>{[{id:"all",label:"All"},{id:"videos",label:"Videos"},{id:"shorts",label:"Shorts"}].map(t=><button key={t.id} onClick={()=>setVtype(t.id)} style={{padding:"5px 16px",borderRadius:"99px",border:`1.5px solid ${vtype===t.id?"rgba(124,58,237,0.7)":"rgba(255,255,255,0.1)"}`,background:vtype===t.id?"rgba(124,58,237,0.15)":"transparent",color:vtype===t.id?"#a78bfa":"rgba(255,255,255,0.5)",fontSize:"11px",fontWeight:"600",cursor:"pointer",fontFamily:"inherit"}}>{t.label}</button>)}</div></div><GB onClick={fetch_} loading={loading} label="✦ Fetch Trending Videos" color="#7c3aed"/></GC>
  {loading&&<SK/>}
  {!loading&&data?.videos?.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"10px"}}>{data.videos.map((v,i)=><GC key={i} style={{display:"flex",gap:"14px",alignItems:"flex-start"}}><div style={{position:"relative",flexShrink:0}}><img src={v.thumbnail} alt="" style={{width:"120px",height:"68px",borderRadius:"8px",objectFit:"cover"}}/><div style={{position:"absolute",top:"4px",left:"4px",background:"rgba(124,58,237,0.9)",borderRadius:"4px",padding:"1px 6px",fontSize:"10px",fontWeight:"800",color:"#fff"}}>#{i+1}</div>{v.is_short&&<div style={{position:"absolute",top:"4px",right:"4px",background:"rgba(255,0,0,0.9)",borderRadius:"4px",padding:"1px 6px",fontSize:"9px",fontWeight:"800",color:"#fff"}}>SHORT</div>}</div><div style={{flex:1,minWidth:0}}><div style={{fontSize:"13px",color:"#fff",fontWeight:"700",lineHeight:1.4,marginBottom:"6px"}}>{v.title}</div><div style={{fontSize:"11px",color:C.muted,marginBottom:"6px"}}>{v.channel}</div><div style={{display:"flex",gap:"12px",flexWrap:"wrap"}}><span style={{fontSize:"11px",color:C.success,fontWeight:"600"}}>👁 {fmtNum(v.views)}</span><span style={{fontSize:"11px",color:"#a78bfa",fontWeight:"600"}}>❤️ {fmtNum(v.likes)}</span><span style={{fontSize:"11px",color:"#60a5fa",fontWeight:"600"}}>💬 {fmtNum(v.comments)}</span><span style={{fontSize:"10px",color:C.muted}}>{v.published}</span></div>{v.tags?.length>0&&<div style={{display:"flex",gap:"4px",flexWrap:"wrap",marginTop:"6px"}}>{v.tags.slice(0,3).map((t,j)=><span key={j} style={{padding:"2px 8px",borderRadius:"99px",background:"rgba(124,58,237,0.1)",border:"1px solid rgba(124,58,237,0.2)",color:"#c4b5fd",fontSize:"10px"}}>{t}</span>)}</div>}</div><a href={`https://youtube.com/watch?v=${v.video_id}`} target="_blank" rel="noreferrer" style={{padding:"6px 12px",borderRadius:"8px",background:"rgba(124,58,237,0.15)",border:"1px solid rgba(124,58,237,0.3)",color:"#c4b5fd",fontSize:"11px",fontWeight:"700",textDecoration:"none",flexShrink:0}}>▶ Watch</a></GC>)}</div>}
  </TC>);}

export function EvergreenScore(){
  const [title,setTitle]=useState("");const [desc,setDesc]=useState("");const [niche,setNiche]=useState("general");const [data,setData]=useState(null);const [loading,setLoading]=useState(false);
  const niches=["General","Gaming","Music","Tech","Education","Entertainment","Food","Fitness","Travel","Finance","Comedy","Motivation","Vlog","Bollywood","Cricket","Startup","DIY","Beauty","Science","Cooking","Crypto","Cars","Pets","News"];
  const analyze=async()=>{if(!title.trim())return;setLoading(true);setData(null);const r=await apiFetch("/youtube-tools/evergreen-score",{title,description:desc,niche});setData(r);setLoading(false);};
  const scoreColor=s=>s>=75?C.success:s>=50?C.yellow:C.danger;
  const scoreLabel=s=>s>=75?"🌲 Highly Evergreen":s>=50?"🌿 Moderately Evergreen":s>=25?"🍂 Trend-Based":"⚡ News-Based";
  return(<TC title="Evergreen Score" icon="🌲"><GC style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>VIDEO TITLE *</div><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. How to Start a YouTube Channel in 2026" style={{width:"100%",padding:"12px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"14px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"12px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>DESCRIPTION (optional)</div><textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Paste your video description for better analysis..." style={{width:"100%",padding:"12px 16px",borderRadius:"12px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",height:"80px",resize:"none",marginBottom:"14px"}}/><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>NICHE</div><div style={{marginBottom:"16px"}}><NP niches={niches} active={niche} onSelect={setNiche} color="#7c3aed"/></div><GB onClick={analyze} loading={loading} label="✦ Analyze Evergreen Score" color="#7c3aed"/></GC>
  {loading&&<SK/>}
  {!loading&&data&&!data.error&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>
    <GC style={{textAlign:"center",borderLeft:"3px solid "+scoreColor(data.evergreen_score)}}><div style={{fontSize:"48px",fontWeight:"900",color:scoreColor(data.evergreen_score)}}>{data.evergreen_score}</div><div style={{fontSize:"16px",fontWeight:"700",color:"#fff",marginBottom:"4px"}}>{scoreLabel(data.evergreen_score)}</div><div style={{display:"flex",justifyContent:"center",gap:"16px",flexWrap:"wrap"}}><span style={{fontSize:"12px",color:C.muted}}>📅 Shelf life: <span style={{color:"#fff",fontWeight:"700"}}>{data.shelf_life}</span></span><span style={{fontSize:"12px",color:C.muted}}>🎯 Best for: <span style={{color:"#fff",fontWeight:"700"}}>{data.best_for}</span></span></div></GC>
    <GC><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"10px"}}>✅ Why this score</div>{data.reasons?.map((r,i)=><div key={i} style={{fontSize:"13px",color:"rgba(255,255,255,0.8)",marginBottom:"6px",paddingLeft:"12px",borderLeft:"2px solid rgba(124,58,237,0.4)"}}>• {r}</div>)}</GC>
    <GC style={{borderLeft:"3px solid #10b981"}}><div style={{fontSize:"11px",fontWeight:"700",color:"#a78bfa",marginBottom:"6px",textTransform:"uppercase"}}>💡 How to Improve</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.8)",lineHeight:1.6}}>{data.improvement}</div></GC>
  </div>}
  </TC>);}

export function DailyVideoIdeas(){
  const [niche,setNiche]=useState("");const [style_,setStyle]=useState("educational");const [lang,setLang]=useState("English");const [data,setData]=useState(null);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(null);
  const niches=["Tech","Finance","Fitness","Food","Gaming","Education","Comedy","Travel","Fashion","Motivation","Bollywood","Cricket","Startup","DIY","Beauty","Spirituality","Parenting","Music","Vlog","Cooking","Science","History","Politics","Crypto","Stock Market","Real Estate","Cars","Pets","Photography","Art","Dance","Yoga","Meditation","Mental Health","Relationships","Books","Movies","Sports","News","Shorts"];
  const styles=["Educational","Entertaining","Vlog","Commentary","Tutorial","Reaction","Storytelling","Documentary"];
  const langs=["English","Hinglish","Hindi","Marathi","Tamil","Bengali"];
  const generate=async()=>{if(!niche.trim())return;setLoading(true);setData(null);const r=await apiFetch("/youtube-tools/daily-ideas",{niche,channel_style:style_,language:lang});setData(r);setLoading(false);};
  const diffColor=d=>d==="Easy"?C.success:d==="Medium"?C.yellow:C.danger;
  return(<TC title="Daily Video Ideas" icon="💡"><GC style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>YOUR NICHE *</div><div style={{marginBottom:"14px"}}><NP niches={niches} active={niche} onSelect={setNiche} color="#7c3aed"/></div><input value={niche} onChange={e=>setNiche(e.target.value)} placeholder="Or type your niche..." style={{width:"100%",padding:"10px 16px",borderRadius:"99px",border:"1.5px solid rgba(255,255,255,0.08)",background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:"13px",fontFamily:"inherit",outline:"none",boxSizing:"border-box",marginBottom:"14px"}}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"16px"}}><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>CHANNEL STYLE</div><NP niches={styles} active={style_} onSelect={setStyle} color="#7c3aed"/></div><div><div style={{fontSize:"11px",fontWeight:"700",color:C.muted,textTransform:"uppercase",letterSpacing:"1px",marginBottom:"8px"}}>LANGUAGE</div><NP niches={langs} active={lang} onSelect={setLang} color="#7c3aed"/></div></div><GB onClick={generate} loading={loading} label="✦ Generate Today's Video Ideas" color="#7c3aed"/></GC>
  {loading&&<SK/>}
  {!loading&&data?.ideas?.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{data.ideas.map((idea,i)=><GC key={i} style={{borderLeft:`3px solid ${diffColor(idea.difficulty)}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:"10px"}}><div style={{flex:1}}><div style={{display:"flex",gap:"8px",alignItems:"center",marginBottom:"4px",flexWrap:"wrap"}}><span style={{fontSize:"10px",fontWeight:"700",color:diffColor(idea.difficulty),background:diffColor(idea.difficulty)+"18",padding:"2px 8px",borderRadius:"99px"}}>{idea.difficulty}</span><span style={{fontSize:"10px",color:C.muted,background:"rgba(255,255,255,0.05)",padding:"2px 8px",borderRadius:"99px"}}>{idea.format}</span><span style={{fontSize:"10px",color:"#a78bfa",fontWeight:"600"}}>📊 {idea.estimated_views}</span></div><div style={{fontSize:"14px",fontWeight:"800",color:"#fff",lineHeight:1.4}}>{idea.title}</div></div><button onClick={()=>{navigator.clipboard.writeText(`Title: ${idea.title}\n\nHook: ${idea.hook}\n\nWhy now: ${idea.why_now}`);setCopied(i);setTimeout(()=>setCopied(null),2000);}} style={{padding:"5px 12px",borderRadius:"99px",border:"1px solid rgba(124,58,237,0.3)",background:"rgba(124,58,237,0.1)",color:copied===i?C.success:"#a78bfa",fontSize:"11px",fontWeight:"700",cursor:"pointer",fontFamily:"inherit",flexShrink:0,marginLeft:"10px"}}>{copied===i?"✓":"Copy"}</button></div><div style={{padding:"10px 12px",borderRadius:"10px",background:"rgba(255,255,255,0.03)",marginBottom:"8px"}}><div style={{fontSize:"10px",fontWeight:"700",color:C.muted,textTransform:"uppercase",marginBottom:"4px"}}>🎣 Hook (First 15 seconds)</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.8)",lineHeight:1.6,fontStyle:"italic"}}>"{idea.hook}"</div></div><div style={{fontSize:"11px",color:"#a78bfa",fontWeight:"600"}}>⏰ Why post now: {idea.why_now}</div></GC>)}</div>}
  </TC>);}
